import os

INTERNAL_SCRIPT_NAME = "ExportClassToCPPH"

PROJECT_INCLUDES_PATH = r"D:\PROJECTS\Visual Studio\EGameSDK\EGameSDK\include"
OUTPUT_PATH = r"D:\PROJECTS\Visual Studio\EGameSDK\_IDAScripts"
HEADER_OUTPUT_PATH = os.path.join(OUTPUT_PATH, "generated")
CACHE_OUTPUT_PATH = os.path.join(OUTPUT_PATH, "cache")
PARSED_VARS_CACHE_FILENAME = os.path.join(CACHE_OUTPUT_PATH, "parsedClassVarsByClass.cache")
PARSED_FUNCS_CACHE_FILENAME = os.path.join(CACHE_OUTPUT_PATH, "parsedFuncsByClass.cache")
LAST_CLICKED_RADIO = 0

DEFAULT_CONFIG = {
    "PROJECT_INCLUDES_PATH": PROJECT_INCLUDES_PATH,
    "OUTPUT_PATH": OUTPUT_PATH,
    "LAST_CLICKED_RADIO": LAST_CLICKED_RADIO,
}