#pragma once
#include <EGSDK\Imports.h>
#include <EGSDK\Engine\rtti\Type.h>
#include <EGSDK\Engine\ttl\list.h>
#include <EGSDK\Engine\ttl\allocator.h>

class CBaseCamera {
#pragma region GENERATED by ExportClassToCPPH.py
public:
	GAME_IMPORT static bool __INTERNAL_crtti_fields_initialized_field;
	GAME_IMPORT static rtti::Type& m_RTTI;

	VIRTUAL_CALL(0, uint64_t*, sub_405720, (char a1), a1);
	VIRTUAL_CALL(1, int64_t, sub_10E8140, (int64_t a1), a1);
	VIRTUAL_CALL(2, int64_t, sub_10E8260, (int64_t a1), a1);
	VIRTUAL_CALL(3, int64_t, sub_10E8390, (int64_t a1), a1);
	VIRTUAL_CALL(4, int64_t, sub_10E8730, (__int128* a1, char a2), a1, a2);
	VIRTUAL_CALL(5, ttl::list<MED::CMaterialTemplate::FieldDefinition, ttl::allocator> const&, fields, ());
	VIRTUAL_CALL(6, SpawnMaskingPath const&, GetSpawnMaskingPath, ());
	VIRTUAL_CALL(7, CRTTIObject* const&, GetValueConstValue, (gui::CActionGraphInstance*), gui::CActionGraphInstance*);
	VIRTUAL_CALL(8, ttl::list<MED::CMaterialTemplate::FieldDefinition, ttl::allocator> const&, _fields1, ());
	VIRTUAL_CALL(9, int64_t, sub_10E8800, ());
	VIRTUAL_CALL(10, int64_t, sub_417620, ());
	VIRTUAL_CALL(11, int64_t, sub_42B070, ());
	VIRTUAL_CALL(12, int64_t, sub_43D650, ());
	VIRTUAL_CALL(13, double, sub_43B610, (int a1, int a2, int a3), a1, a2, a3);
	VIRTUAL_CALL(14, int64_t, sub_43C1F0, (int a1), a1);
	VIRTUAL_CALL(15, int64_t, sub_43CAC0, ());
	VIRTUAL_CALL(16, const char*, sub_419DF0, ());
	VIRTUAL_CALL(17, int64_t, sub_40B260, ());
	VIRTUAL_CALL(18, void, sub_4136E0, (float a1, float a2, float a3, int a4), a1, a2, a3, a4);
	VIRTUAL_CALL(19, void, sub_4136A0, (float a1, float a2), a1, a2);
	VIRTUAL_CALL(20, void, sub_41FFA0, ());
	VIRTUAL_CALL(21, int64_t, sub_43D620, (float a1), a1);
	VIRTUAL_CALL(22, float, sub_41DD20, ());
	VIRTUAL_CALL(23, char*, sub_419B40, ());
	VIRTUAL_CALL(24, int64_t, sub_4461D0, (int64_t a1, int64_t a2), a1, a2);

	GAME_IMPORT static rtti::Type& typeinfo();
private:
	GAME_IMPORT static bool __INTERNAL_crtti_fields_initialized_function();
public:
	GAME_IMPORT static CRTTI* GetSTTI();
private:
	GAME_IMPORT static rtti::Type& __INTERNAL_type_factory();
	GAME_IMPORT static CRTTI* __INTERNAL_crtti_factory();
public:
	GAME_IMPORT static CBaseCamera::CBaseCameraMemento const* LoadMemento(fs::ifile&);
#pragma endregion
};
