#pragma once
#include <optional>
#include <memory>
#include <EGSDK\Imports.h>
#include <EGSDK\Engine\rtti.h>
#include <EGSDK\Engine\IRTTIEnumerationTyped.h>
#include <EGSDK\Engine\ttl\vector.h>
#include <EGSDK\Engine\ttl\string_base.h>
#include <EGSDK\Engine\ttl\list.h>
#include <EGSDK\Engine\ttl\set.h>
#include <EGSDK\Engine\ttl\less.h>
#include <EGSDK\Engine\ttl\allocator.h>
#include <EGSDK\Engine\ttl\function_ref.h>
#include <EGSDK\Engine\ttl\vector_allocators\heap_allocator.h>
#include <EGSDK\Engine\Uid.h>
#include <EGSDK\Engine\IPtrResolver.h>

class CRTTI;
class CRTTIObject;
class ILevel;
class IGSObject;
class MED {
	public:
		struct SModelOutfitGroup;
};

class cbs {
public:
	struct WorldIndex;
	
	class detail {
	public:
		enum Handle;
	};

	class prop {
	public:
		class IPropertySet;
	};

	class msg {
	public:
		class RttiMessageDispatcher {
#pragma region GENERATED by ExportClassToCPPH.py
		public:
			VIRTUAL_CALL(0, uint64_t*, unknown_libname_171, (char a1), a1);
#pragma endregion
		};

		class IMessagePipeSet {
#pragma region GENERATED by ExportClassToCPPH.py
		public:
			VIRTUAL_CALL(0, uint64_t*, sub_1233F0, (char a1), a1);
			virtual void _StrippedVFunc1() = 0;
			virtual void _StrippedVFunc2() = 0;
			virtual void _StrippedVFunc3() = 0;
			virtual void _StrippedVFunc4() = 0;
			virtual void _StrippedVFunc5() = 0;
			virtual void _StrippedVFunc6() = 0;
			virtual void _StrippedVFunc7() = 0;
			virtual void _StrippedVFunc8() = 0;
			virtual void _StrippedVFunc9() = 0;
			virtual void _StrippedVFunc10() = 0;
			virtual void _StrippedVFunc11() = 0;
			GAME_IMPORT virtual ttl::string_base<char> ToString(CRTTIObject const*) const;
#pragma endregion
		};
	};

	class Call {
	public:
		enum TYPE;

#pragma region GENERATED by ExportClassToCPPH.py
	public:
		GAME_IMPORT static IRTTIEnumerationTyped<cbs::Call::TYPE> const* GetRTTI();
#pragma endregion
	};

	class CBaseObject {
#pragma region GENERATED by ExportClassToCPPH.py
	public:
		GAME_IMPORT static rtti::Type& m_RTTI;
		GAME_IMPORT static bool __INTERNAL_crtti_fields_initialized_field;

		VIRTUAL_CALL(0, void, SetPlatform, ());
		VIRTUAL_CALL(1, cbs::CBaseObject*, sub_11A890, (char a1), a1);
		GAME_IMPORT virtual CRTTI const* GetRTTI() const;
		VIRTUAL_CALL(3, CRTTI const*, _GetRTTI1, ());
		VIRTUAL_CALL(4, MED::SModelOutfitGroup const*, unassigned, ());
		VIRTUAL_CALL(5, MED::SModelOutfitGroup const*, _unassigned1, ());
		VIRTUAL_CALL(6, MED::SModelOutfitGroup const*, _unassigned2, ());
		VIRTUAL_CALL(7, MED::SModelOutfitGroup const*, _unassigned3, ());
		VIRTUAL_CALL(8, int64_t, RunUnitTests, ());
		VIRTUAL_CALL(9, int64_t, _RunUnitTests1, ());
		GAME_IMPORT virtual void GetPrivateObjects(ttl::list<IGSObject*, ttl::allocator>*, bool, bool);
		GAME_IMPORT virtual void DestroyPrivateObjects();
		VIRTUAL_CALL(12, int64_t, _RunUnitTests2, ());
		GAME_IMPORT virtual void GetAllObjects(ttl::vector<IGSObject*, ttl::vector_allocators::heap_allocator<IGSObject*>, 1>&, bool);
		GAME_IMPORT virtual void GetAllObjects(ttl::set<CRTTIObject*, ttl::less<CRTTIObject*>, ttl::allocator>&, ttl::set<CRTTIObject*, ttl::less<CRTTIObject*>, ttl::allocator>&, bool, std::optional<ttl::function_ref<bool(CRTTIObject*)>>);
		VIRTUAL_CALL(15, bool, updateRttiParams, ());
		VIRTUAL_CALL(16, void, _SetPlatform1, ());
		GAME_IMPORT virtual char const* GetString(char const*) const;
		VIRTUAL_CALL(18, void, _SetPlatform2, ());
		VIRTUAL_CALL(19, bool, _updateRttiParams1, ());
		VIRTUAL_CALL(20, void, _SetPlatform3, ());
		VIRTUAL_CALL(21, MED::SModelOutfitGroup const*, _unassigned4, ());
		VIRTUAL_CALL(22, void, _SetPlatform4, ());
		GAME_IMPORT virtual Uid const& GetUid() const;
		VIRTUAL_CALL(24, bool, _updateRttiParams2, ());
		VIRTUAL_CALL(25, bool, _updateRttiParams3, ());
		VIRTUAL_CALL(26, bool, _updateRttiParams4, ());
		VIRTUAL_CALL(27, bool, _updateRttiParams5, ());
		VIRTUAL_CALL(28, bool, _updateRttiParams6, ());
		VIRTUAL_CALL(29, bool, _updateRttiParams7, ());
		VIRTUAL_CALL(30, bool, _updateRttiParams8, ());
		VIRTUAL_CALL(31, bool, _updateRttiParams9, ());
		VIRTUAL_CALL(32, bool, _updateRttiParams10, ());
		GAME_IMPORT virtual void CallVoidMethod(char const*, ...);
		GAME_IMPORT virtual cbs::msg::IMessagePipeSet const& GetMessagePipeSet() const;
		VIRTUAL_CALL(35, int64_t, _RunUnitTests3, ());
		VIRTUAL_CALL(36, MED::SModelOutfitGroup const*, _unassigned5, ());
		VIRTUAL_CALL(37, MED::SModelOutfitGroup const*, _unassigned6, ());
		VIRTUAL_CALL(38, MED::SModelOutfitGroup const*, _unassigned7, ());
		VIRTUAL_CALL(39, MED::SModelOutfitGroup const*, _unassigned8, ());
		GAME_IMPORT virtual cbs::prop::IPropertySet const& GetPropertySet() const;
		VIRTUAL_CALL(41, void, _SetPlatform5, ());
		VIRTUAL_CALL(42, int64_t, _RunUnitTests4, ());
		GAME_IMPORT virtual bool LoadField(CRTTIField const*, unsigned char, fs::ifile&, IPtrResolver&, bool);
		GAME_IMPORT virtual void LoadFields(dom::IReader::Object const&, IPtrResolver&, bool, bool (*)(char const*, CRTTIObject*));
		GAME_IMPORT virtual void LoadFields(ITextDeserializer&, IPtrResolver&, bool);
		GAME_IMPORT virtual void LoadFields(fs::ifile&, IPtrResolver&, bool);
		GAME_IMPORT virtual void SaveFields(dom::IWriter&, ERTTIFlags, bool) const;
		GAME_IMPORT virtual int ToBufferReplicated(char*, int);
		GAME_IMPORT virtual int FromBufferReplicated(char*, int);
		GAME_IMPORT virtual int GetBufferReplicatedDataSize();
		VIRTUAL_CALL(51, void, _SetPlatform6, ());
		VIRTUAL_CALL(52, static bool, ValidateVec4, (IGSObject const*, vec4 const&), const*, const&);
		GAME_IMPORT virtual bool CopyFields(CRTTIObject const*, bool);
		GAME_IMPORT virtual bool CopyPointerFields(CRTTIObject const*);
		GAME_IMPORT virtual bool ExchangePointerFields(CRTTIObject*);
		VIRTUAL_CALL(56, int64_t, _RunUnitTests5, ());
		VIRTUAL_CALL(57, int64_t, _RunUnitTests6, ());
		VIRTUAL_CALL(58, int64_t, _RunUnitTests7, ());
		GAME_IMPORT virtual SRttiNetPointer GetNetPointer() const;
		VIRTUAL_CALL(60, int64_t, _RunUnitTests8, ());
		GAME_IMPORT virtual ttl::string_base<char> GetDebugDescription() const;
		GAME_IMPORT virtual void CalcMemoryUsage(SObjectMemoryUsage&) const;
		VIRTUAL_CALL(63, void, _SetPlatform7, ());
		GAME_IMPORT virtual bool GetValidFieldValuesEditor(CRTTIField const&, ttl::vector<ttl::string_base<char>, ttl::vector_allocators::heap_allocator<ttl::string_base<char>>, 1>&, ttl::vector<ttl::string_base<char>, ttl::vector_allocators::heap_allocator<ttl::string_base<char>>, 1>&);
		VIRTUAL_CALL(65, bool, _updateRttiParams11, ());
		VIRTUAL_CALL(66, static bool, _ValidateVec41, (IGSObject const* a1, vec4 const& a2), a1, a2);
		VIRTUAL_CALL(67, int64_t, _RunUnitTests9, ());
		GAME_IMPORT virtual ttl::string_base<char> ValueToString(CRTTIObject* const&) const;
		GAME_IMPORT virtual bool IsFieldChanged(CRTTIField const*) const;
		GAME_IMPORT virtual void SetFieldChangedFlag(CRTTIField const*, bool);
		VIRTUAL_CALL(71, bool, _updateRttiParams12, ());
		GAME_IMPORT virtual bool OnFieldChanged2(CRTTIField const*, bool);
		VIRTUAL_CALL(73, void, _SetPlatform8, ());
		VIRTUAL_CALL(74, int64_t, _RunUnitTests10, ());
		VIRTUAL_CALL(75, void, _SetPlatform9, ());
		VIRTUAL_CALL(76, bool, _updateRttiParams13, ());
	protected:
		GAME_IMPORT virtual bool OnFieldChanged(CRTTIField const*, bool);
	public:
		VIRTUAL_CALL(78, bool, _updateRttiParams14, ());
		VIRTUAL_CALL(79, bool, _updateRttiParams15, ());
		VIRTUAL_CALL(80, int64_t, _RunUnitTests11, ());
		VIRTUAL_CALL(81, int64_t, _RunUnitTests12, ());
		VIRTUAL_CALL(82, void, _SetPlatform10, ());
		GAME_IMPORT virtual void Query(IBaseValidator&, ttl::vector<CRTTIObject*, ttl::vector_allocators::heap_allocator<CRTTIObject*>, 1>&) const;
		VIRTUAL_CALL(84, void, _SetPlatform11, ());
	protected:
		GAME_IMPORT virtual void OnRelease(cbs::contracts::ApiComponentOnRelease);

	public:
		GAME_IMPORT static CRTTI* GetSTTI();
		GAME_IMPORT cbs::WorldIndex GetWorldId() const;
		GAME_IMPORT CLevel* GetCLevel() const;
	protected:
		GAME_IMPORT CBaseObject();
		GAME_IMPORT bool GetLowLevelActive() const;
	private:
		GAME_IMPORT static bool __INTERNAL_crtti_fields_initialized_function();
	public:
		GAME_IMPORT static rtti::Type& typeinfo();
	protected:
		GAME_IMPORT void SetLowLevelActive(bool);
	private:
		GAME_IMPORT void InvalidateHandle();
	public:
		GAME_IMPORT void InvalidateHandle(cbs::contracts::ApiInvalidatePointer);
		GAME_IMPORT void Release();
		GAME_IMPORT CBaseObject(cbs::CBaseObject const&);
		GAME_IMPORT ILevel* GetILevel() const;
	private:
		GAME_IMPORT static CRTTI* __INTERNAL_crtti_factory();
		GAME_IMPORT static rtti::Type& __INTERNAL_type_factory();
#pragma endregion
	};

	template<typename T1, typename T2>
	class CAbstractSystem;

	template<typename T1>
	class CSystemWorldData;

	class CComponent {
#pragma region GENERATED by ExportClassToCPPH.py
	public:
		GAME_IMPORT static cbs::CAbstractSystem<cbs::CComponent, cbs::CSystemWorldData<cbs::CComponent>>& s_System;
		GAME_IMPORT static bool __INTERNAL_crtti_fields_initialized_field;
		GAME_IMPORT static rtti::Type& m_RTTI;

		VIRTUAL_CALL(0, void, SetPlatform, ());
		VIRTUAL_CALL(1, cbs::CBaseObject*, sub_11ADA0, (char a1), a1);
		GAME_IMPORT virtual CRTTI const* GetRTTI() const;
		VIRTUAL_CALL(3, CRTTI const*, _GetRTTI1, ());
		VIRTUAL_CALL(4, MED::SModelOutfitGroup const*, unassigned, ());
		VIRTUAL_CALL(5, MED::SModelOutfitGroup const*, _unassigned1, ());
		VIRTUAL_CALL(6, MED::SModelOutfitGroup const*, _unassigned2, ());
		VIRTUAL_CALL(7, MED::SModelOutfitGroup const*, _unassigned3, ());
		VIRTUAL_CALL(8, int64_t, RunUnitTests, ());
		VIRTUAL_CALL(9, int64_t, _RunUnitTests1, ());
		GAME_IMPORT virtual void GetPrivateObjects(ttl::list<IGSObject*, ttl::allocator>*, bool, bool);
		GAME_IMPORT virtual void DestroyPrivateObjects();
		VIRTUAL_CALL(12, int64_t, _RunUnitTests2, ());
		GAME_IMPORT virtual void GetAllObjects(ttl::vector<IGSObject*, ttl::vector_allocators::heap_allocator<IGSObject*>, 1>&, bool);
		GAME_IMPORT virtual void GetAllObjects(ttl::set<CRTTIObject*, ttl::less<CRTTIObject*>, ttl::allocator>&, ttl::set<CRTTIObject*, ttl::less<CRTTIObject*>, ttl::allocator>&, bool, std::optional<ttl::function_ref<bool(CRTTIObject*)>>);
		VIRTUAL_CALL(15, bool, updateRttiParams, ());
		VIRTUAL_CALL(16, void, _SetPlatform1, ());
		GAME_IMPORT virtual char const* GetString(char const*) const;
		VIRTUAL_CALL(18, void, _SetPlatform2, ());
		VIRTUAL_CALL(19, bool, _updateRttiParams1, ());
		VIRTUAL_CALL(20, void, _SetPlatform3, ());
		VIRTUAL_CALL(21, MED::SModelOutfitGroup const*, _unassigned4, ());
		VIRTUAL_CALL(22, void, _SetPlatform4, ());
		GAME_IMPORT virtual Uid const& GetUid() const;
		VIRTUAL_CALL(24, bool, _updateRttiParams2, ());
		VIRTUAL_CALL(25, bool, _updateRttiParams3, ());
		VIRTUAL_CALL(26, bool, _updateRttiParams4, ());
		VIRTUAL_CALL(27, bool, _updateRttiParams5, ());
		VIRTUAL_CALL(28, bool, _updateRttiParams6, ());
		VIRTUAL_CALL(29, bool, _updateRttiParams7, ());
		VIRTUAL_CALL(30, bool, _updateRttiParams8, ());
		VIRTUAL_CALL(31, bool, _updateRttiParams9, ());
		VIRTUAL_CALL(32, bool, _updateRttiParams10, ());
		GAME_IMPORT virtual void CallVoidMethod(char const*, ...);
		GAME_IMPORT virtual cbs::msg::IMessagePipeSet const& GetMessagePipeSet() const;
		VIRTUAL_CALL(35, int64_t, _RunUnitTests3, ());
		VIRTUAL_CALL(36, MED::SModelOutfitGroup const*, _unassigned5, ());
		VIRTUAL_CALL(37, MED::SModelOutfitGroup const*, _unassigned6, ());
		VIRTUAL_CALL(38, MED::SModelOutfitGroup const*, _unassigned7, ());
		VIRTUAL_CALL(39, MED::SModelOutfitGroup const*, _unassigned8, ());
		GAME_IMPORT virtual cbs::prop::IPropertySet const& GetPropertySet() const;
		VIRTUAL_CALL(41, void, _SetPlatform5, ());
		VIRTUAL_CALL(42, int64_t, _RunUnitTests4, ());
		GAME_IMPORT virtual bool LoadField(CRTTIField const*, unsigned char, fs::ifile&, IPtrResolver&, bool);
		GAME_IMPORT virtual void LoadFields(dom::IReader::Object const&, IPtrResolver&, bool, bool (*)(char const*, CRTTIObject*));
		GAME_IMPORT virtual void LoadFields(ITextDeserializer&, IPtrResolver&, bool);
		GAME_IMPORT virtual void LoadFields(fs::ifile&, IPtrResolver&, bool);
		GAME_IMPORT virtual void SaveFields(dom::IWriter&, ERTTIFlags, bool) const;
		GAME_IMPORT virtual int ToBufferReplicated(char*, int);
		GAME_IMPORT virtual int FromBufferReplicated(char*, int);
		GAME_IMPORT virtual int GetBufferReplicatedDataSize();
		VIRTUAL_CALL(51, void, _SetPlatform6, ());
		VIRTUAL_CALL(52, static bool, ValidateVec4, (IGSObject const*, vec4 const&), const*, const&);
		GAME_IMPORT virtual bool CopyFields(CRTTIObject const*, bool);
		GAME_IMPORT virtual bool CopyPointerFields(CRTTIObject const*);
		GAME_IMPORT virtual bool ExchangePointerFields(CRTTIObject*);
		VIRTUAL_CALL(56, int64_t, _RunUnitTests5, ());
		GAME_IMPORT virtual IGSObject* FindObjectByNetPointer(SRttiNetPointer const&) const;
		GAME_IMPORT virtual cbs::CEntity* FindEntityByNetPointer(SRttiNetPointer const&) const;
		GAME_IMPORT virtual SRttiNetPointer GetNetPointer() const;
		GAME_IMPORT virtual cbs::pcid_t GetPcId() const;
		GAME_IMPORT virtual ttl::string_base<char> GetDebugDescription() const;
		GAME_IMPORT virtual void CalcMemoryUsage(SObjectMemoryUsage&) const;
		VIRTUAL_CALL(63, void, _SetPlatform7, ());
		GAME_IMPORT virtual bool GetValidFieldValuesEditor(CRTTIField const&, ttl::vector<ttl::string_base<char>, ttl::vector_allocators::heap_allocator<ttl::string_base<char>>, 1>&, ttl::vector<ttl::string_base<char>, ttl::vector_allocators::heap_allocator<ttl::string_base<char>>, 1>&);
		VIRTUAL_CALL(65, bool, _updateRttiParams11, ());
		VIRTUAL_CALL(66, static bool, _ValidateVec41, (IGSObject const* a1, vec4 const& a2), a1, a2);
		VIRTUAL_CALL(67, int64_t, _RunUnitTests6, ());
		GAME_IMPORT virtual ttl::string_base<char> ValueToString(CRTTIObject* const&) const;
		GAME_IMPORT virtual bool IsFieldChanged(CRTTIField const*) const;
		GAME_IMPORT virtual void SetFieldChangedFlag(CRTTIField const*, bool);
		VIRTUAL_CALL(71, bool, _updateRttiParams12, ());
		GAME_IMPORT virtual bool OnFieldChanged2(CRTTIField const*, bool);
		VIRTUAL_CALL(73, void, _SetPlatform8, ());
		VIRTUAL_CALL(74, int64_t, _RunUnitTests7, ());
		VIRTUAL_CALL(75, void, _SetPlatform9, ());
		VIRTUAL_CALL(76, bool, _updateRttiParams13, ());
	protected:
		GAME_IMPORT virtual bool OnFieldChanged(CRTTIField const*, bool);
	public:
		VIRTUAL_CALL(78, bool, _updateRttiParams14, ());
		VIRTUAL_CALL(79, bool, _updateRttiParams15, ());
		VIRTUAL_CALL(80, int64_t, _RunUnitTests8, ());
		VIRTUAL_CALL(81, int64_t, _RunUnitTests9, ());
		VIRTUAL_CALL(82, void, _SetPlatform10, ());
		GAME_IMPORT virtual void Query(IBaseValidator&, ttl::vector<CRTTIObject*, ttl::vector_allocators::heap_allocator<CRTTIObject*>, 1>&) const;
		GAME_IMPORT virtual void OnDestroy(cbs::contracts::ApiComponentOnDestroy);
		GAME_IMPORT virtual void OnRelease(cbs::contracts::ApiComponentOnRelease);
		GAME_IMPORT virtual cbs::CSystemBase& GetSystem() const;
		GAME_IMPORT virtual void OnConstructObject(cbs::contracts::ApiComponentOnConstructObject);
		GAME_IMPORT virtual void OnPreCreate(cbs::contracts::ApiComponentOnPreCreate);
		VIRTUAL_CALL(89, void, _SetPlatform11, ());
		VIRTUAL_CALL(90, void, _SetPlatform12, ());
	protected:
		GAME_IMPORT virtual void OnReplicationPrepare();
	public:
		VIRTUAL_CALL(92, bool, _updateRttiParams16, ());
		VIRTUAL_CALL(93, int64_t, _RunUnitTests10, ());
		VIRTUAL_CALL(94, int64_t, _RunUnitTests11, ());
		VIRTUAL_CALL(95, bool, _updateRttiParams17, ());
		VIRTUAL_CALL(96, void, _SetPlatform13, ());
		GAME_IMPORT virtual ICoWorldXform const* GetXformComponent() const;
		VIRTUAL_CALL(98, ICoWorldXform const*, _GetXformComponent1, ());
		VIRTUAL_CALL(99, void, _SetPlatform14, ());
		VIRTUAL_CALL(100, void, _SetPlatform15, ());
		VIRTUAL_CALL(101, void, _SetPlatform16, ());
		VIRTUAL_CALL(102, static bool, _ValidateVec42, (IGSObject const* a1, vec4 const& a2), a1, a2);
		VIRTUAL_CALL(103, void, _SetPlatform17, ());
		VIRTUAL_CALL(104, void, _SetPlatform18, ());
		VIRTUAL_CALL(105, int64_t, _RunUnitTests12, ());
	protected:
		GAME_IMPORT virtual bool IsCreated() const;
		GAME_IMPORT virtual void OnResolvePrefab(SpawnContext const&, PrefabResolveContext const&);
	public:
		VIRTUAL_CALL(108, void, _SetPlatform19, ());
		VIRTUAL_CALL(109, void, _SetPlatform20, ());
	protected:
		GAME_IMPORT virtual void ApplyActivate(bool);
		GAME_IMPORT virtual void ApplyDeactivate(bool);
		GAME_IMPORT virtual void CallPendingActivationHandlers(CDeferredCallSystem*);
	public:
		VIRTUAL_CALL(113, void, _SetPlatform21, ());
		VIRTUAL_CALL(114, void, _SetPlatform22, ());
		VIRTUAL_CALL(115, void, _SetPlatform23, ());
		VIRTUAL_CALL(116, void, _OnReplicationPrepare1, ());
		VIRTUAL_CALL(117, void, _SetPlatform24, ());
	protected:
		GAME_IMPORT virtual void OnReplicationResolve();
	public:
		VIRTUAL_CALL(119, void, _SetPlatform25, ());
		VIRTUAL_CALL(120, void, _SetPlatform26, ());
		VIRTUAL_CALL(121, void, _SetPlatform27, ());
		VIRTUAL_CALL(122, void, _SetPlatform28, ());
		VIRTUAL_CALL(123, void, _SetPlatform29, ());
		VIRTUAL_CALL(124, void, _SetPlatform30, ());
		VIRTUAL_CALL(125, void, _SetPlatform31, ());

		GAME_IMPORT void CallRegistered();
	private:
		GAME_IMPORT static CRTTI* __INTERNAL_crtti_factory();
	public:
		GAME_IMPORT static cbs::CAbstractSystem<cbs::CComponent, cbs::CSystemWorldData<cbs::CComponent>>& GetSystemInstance();
		GAME_IMPORT void MsgDeactivate();
	protected:
		GAME_IMPORT void DeactivateInternal(bool);
	public:
		GAME_IMPORT bool IsActive() const;
		GAME_IMPORT Replication::IObject& ReplicationObject() const;
		GAME_IMPORT cbs::CSystemWorldData<cbs::CComponent>& GetWorldDataInstance();
		GAME_IMPORT bool AllComponentFlagsSet(cbs::FComponent::TYPE) const;
	protected:
		GAME_IMPORT void SetFlags(cbs::FComponent::TYPE, bool);
	public:
		GAME_IMPORT bool WasRegistered() const;
		GAME_IMPORT void MakeFullyInitialized(cbs::contracts::ApiMakeFullyInitializedComponent);
		GAME_IMPORT bool IsAlive() const;
		GAME_IMPORT void ActivateByParent(bool);
		GAME_IMPORT void Activate();
	protected:
		GAME_IMPORT void ClearFlags(cbs::FComponent::TYPE, bool);
	public:
		GAME_IMPORT void MsgActivate();
		GAME_IMPORT CComponent(cbs::CComponent const&);
		GAME_IMPORT static rtti::Type& typeinfo();
	protected:
		GAME_IMPORT void ActivateInternal(bool);
	private:
		GAME_IMPORT static bool SetSelfActive(CRTTIObject*, bool const&);
	public:
		GAME_IMPORT static CRTTI* GetSTTI();
		GAME_IMPORT void DeactivateByParent(bool);
		GAME_IMPORT void SetComponentFlags(cbs::FComponent::TYPE);
		GAME_IMPORT void ClearComponentFlags(cbs::FComponent::TYPE);
	private:
		GAME_IMPORT static rtti::Type& __INTERNAL_type_factory();
	protected:
		GAME_IMPORT CComponent();
	public:
		GAME_IMPORT static void RegisterSTTI(CRTTI*);
	private:
		GAME_IMPORT static void GetSelfActive(CRTTIObject const*, bool&);
		GAME_IMPORT static bool __INTERNAL_crtti_fields_initialized_function();
	public:
		GAME_IMPORT static cbs::CSystemWorldData<cbs::CComponent>& GetWorldDataInstance(cbs::WorldIndex);
#pragma endregion
	};

	class CSystemBase;
	class CSystemCallManager {
#pragma region GENERATED by ExportClassToCPPH.py
	public:
		VIRTUAL_CALL(0, cbs::CSystemCallManager*, sub_4034E0, (char a1), a1);
	protected:
		GAME_IMPORT virtual void AddCall(cbs::CComponent*, void (*)(cbs::CComponentBase*), cbs::Call::TYPE);
		GAME_IMPORT virtual void RemoveCall(cbs::CComponent*, void (*)(cbs::CComponentBase*), cbs::Call::TYPE);

	public:
		GAME_IMPORT void UnregisterCalls(cbs::CComponent*);
		GAME_IMPORT CSystemCallManager(cbs::CSystemBase*);
		GAME_IMPORT bool IsEmpty() const;
		GAME_IMPORT void InvokeSystemCalls(cbs::WorldIndex, cbs::Call::TYPE, char const*);
		GAME_IMPORT void GetFrameStats(cbs::CallManagerFrameStats&) const;
	private:
		GAME_IMPORT void Debug_EnsureSingleSlotsCreated();
	public:
		GAME_IMPORT void InvokeSingleCalls(cbs::WorldIndex, cbs::Call::TYPE, bool, char const*);
	protected:
		GAME_IMPORT virtual void RemoveSystemCall(cbs::WorldIndex, cbs::ICallable*, void*, void (* const&)(void*, cbs::WorldIndex, cbs::Call::TYPE), cbs::Call::TYPE);
	private:
		GAME_IMPORT static cbs::Call::TYPE GetSlot(cbs::Call::TYPE);
	protected:
		GAME_IMPORT virtual void AddSystemCall(cbs::WorldIndex, cbs::ICallable*, void*, void (* const&)(void*, cbs::WorldIndex, cbs::Call::TYPE), cbs::Call::TYPE);
#pragma endregion
	};

	class CSystemBase {
#pragma region GENERATED by ExportClassToCPPH.py
	public:
		VIRTUAL_CALL(0, uint64_t*, sub_462480, (char a1), a1);
		virtual void _StrippedVFunc1() = 0;
		virtual void _StrippedVFunc2() = 0;
		virtual void _StrippedVFunc3() = 0;
		virtual void _StrippedVFunc4() = 0;
		virtual void _StrippedVFunc5() = 0;
		virtual void _StrippedVFunc6() = 0;
		GAME_IMPORT virtual void Release(cbs::detail::Handle);
		virtual void _StrippedVFunc7() = 0;
		virtual void _StrippedVFunc8() = 0;
		virtual void _StrippedVFunc9() = 0;

		GAME_IMPORT static uint32_t Count(cbs::WorldIndex, CRTTI const*, bool);
		GAME_IMPORT static uint32_t Count(cbs::WorldIndex, rtti::Type const&, bool);
		GAME_IMPORT bool CanInvokeFrame(uint32_t) const;
		GAME_IMPORT bool IsAbstract() const;
		GAME_IMPORT cbs::CSystemCallManager& GetSystemCallManager();
		GAME_IMPORT void CallSystemHandlers(cbs::WorldIndex, cbs::Call::TYPE);
		GAME_IMPORT CSystemBase(uint32_t);
		GAME_IMPORT bool TryReleaseCallManager();
		GAME_IMPORT void CallHandlers(cbs::WorldIndex, cbs::Call::TYPE, bool);
		GAME_IMPORT void RegisterAsCallableSystem();
		GAME_IMPORT void RegisterAsCallable();
#pragma endregion
	};

	class Prefab {
#pragma region GENERATED by ExportClassToCPPH.py
	public:
		GAME_IMPORT static char const* const s_KeyPid;
		GAME_IMPORT static char const* const s_KeyCustomExteriorsDistance;
		GAME_IMPORT static char const* const s_KeyInit;
		GAME_IMPORT static int const PROPERTY_CONTAINER_SUB_OBJECT_IDX;
		GAME_IMPORT static char const* const WORKCOPY_POSTFIX;
		GAME_IMPORT static char const* const s_KeyUser;
		GAME_IMPORT static char const* const s_KeyClass;
		GAME_IMPORT static char const* const s_KeyProperties;
		GAME_IMPORT static char const* const LOD0_POSTFIX;
		GAME_IMPORT static char const* const s_KeyLodAssetName;
		GAME_IMPORT static char const* const s_KeyLodType;
		GAME_IMPORT static char const* const s_KeyLod;
		GAME_IMPORT static char const* const LOD1_IN_LOD2_POSTFIX;
		GAME_IMPORT static char const* const INT_FLT_POSTFIX;
		GAME_IMPORT static char const* const s_KeyBindings;
		GAME_IMPORT static char const* const s_KeyComponents;
		GAME_IMPORT static char const* const MESH_FILE_EXT;
		GAME_IMPORT static char const* const MAP3D_POSTFIX;
		GAME_IMPORT static char const* const s_KeyInterface;
		GAME_IMPORT static char const* const s_KeyIgnorePresetClassNameValidation;
		GAME_IMPORT static char const* const s_KeySpawnType;
		GAME_IMPORT static char const* const INTDTL_FLT_POSTFIX;
		GAME_IMPORT static char const* const s_KeyDestinationFields;
		GAME_IMPORT static char const* const PREFAB_DEFAULT;
		GAME_IMPORT static char const* const PREFAB_FILE_EXT;
		GAME_IMPORT static char const* const s_KeyExtents;
		GAME_IMPORT static char const* const LOD1_POSTFIX;
		GAME_IMPORT static char const* const s_KeyRuntimeData;
		GAME_IMPORT static char const* const s_KeyDetailSpawnType;
		GAME_IMPORT static char const* const LOD1_NAME;
		GAME_IMPORT static char const* const s_KeyName;
		GAME_IMPORT static char const* const LOD2_NAME;
		GAME_IMPORT static char const* const s_PrefabInterfaces;
		GAME_IMPORT static char const* const s_KeySourceUuid;
		GAME_IMPORT static char const* const EXT_FLT_POSTFIX;
		GAME_IMPORT static char const* const LOD0_NAME;
		GAME_IMPORT static char const* const LOD_TERRAIN_POSTFIX;
		GAME_IMPORT static char const* const s_KeyDestinationUuid;
		GAME_IMPORT static char const* const MATERIAL_FILE_EXT;
		GAME_IMPORT static char const* const s_KeyPipes;
		GAME_IMPORT static char const* const s_KeyDestination;
		GAME_IMPORT static char const* const EXTDTL_FLT_POSTFIX;
		GAME_IMPORT static char const* const s_KeyVirtualFields;
		GAME_IMPORT static char const* const GENPIN_INFIX;
		GAME_IMPORT static char const* const s_KeyVersion;
		GAME_IMPORT static char const* const s_KeyDependenciesHash;
		GAME_IMPORT static char const* const s_KeySource;
		GAME_IMPORT static char const* const s_KeyUseCacheToConnectPipes;
		GAME_IMPORT static char const* const LOD2_POSTFIX;
		GAME_IMPORT static char const* const s_KeyFilename;
		GAME_IMPORT static char const* const s_KeyEditorOnly;
		GAME_IMPORT static char const* const s_KeyPrefabEditorData;
		GAME_IMPORT static char const* const NONFLT_POSTFIX;
		GAME_IMPORT static char const* const FLT_POSTFIX;
		GAME_IMPORT static char const* const s_KeyProductionState;
		GAME_IMPORT static char const* const PREFABDUMP_FILE_EXT;

		VIRTUAL_CALL(0, cbs::Prefab*, sub_1214E0, (char a1), a1);
	private:
		GAME_IMPORT virtual void ReleaseUnusedMemory();
	public:
		GAME_IMPORT virtual void InitializeRttiReplication();
		VIRTUAL_CALL(3, void, SetPlatform, ());
		VIRTUAL_CALL(4, int64_t, RunUnitTests, ());
		VIRTUAL_CALL(5, int64_t, _RunUnitTests1, ());
		VIRTUAL_CALL(6, int64_t, _RunUnitTests2, ());
	private:
		GAME_IMPORT virtual CRTTI::SEditorData* CreateEditorData();
	public:
		GAME_IMPORT virtual ttl::string_base<char> ClassWriterCompare(CRTTI const*, CRTTI const*, CRTTI const&) const;
		VIRTUAL_CALL(9, bool, updateRttiParams, ());
	private:
		GAME_IMPORT virtual void Preprocess_Internal(bool);

		GAME_IMPORT void ConnectComponents(PrefabResolveContext const&, int) const;
		GAME_IMPORT void SavePipeBindings(dom::IWriter&) const;
	public:
		GAME_IMPORT void SetFormat(dom::EFormat::TYPE);
	private:
		GAME_IMPORT void ProcessMatrixByRandomizer(cbs::CEntity*, SpawnContext const&, mtx34&) const;
		GAME_IMPORT void UpdateReplicationInfo(CRTTI const*);
		GAME_IMPORT void ResolvePipeIsPartOfBindingScript(cbs::PipeBinding const&) const;
		GAME_IMPORT bool Parse(dom::IReader::Value const&);
	public:
		GAME_IMPORT static ttl::string_base<char> GetOriginalPrefabName(char const*);
		GAME_IMPORT cbs::PrefabElement const* FindComponent(cbs::pcid_t) const;
		GAME_IMPORT cbs::ParseInfo& GetParseInfo();
		GAME_IMPORT cbs::pcid_t AddPrefabComponent(cbs::PrefabElement*, int);
		GAME_IMPORT cbs::PrefabEntityComponent const* FindPrefabEntityComponent(cbs::Prefab const*) const;
		GAME_IMPORT ttl::vector<cbs::PrefabElement*, ttl::vector_allocators::heap_allocator<cbs::PrefabElement*>, 1> const& GetPrefabComponents() const;
		GAME_IMPORT cbs::Prefab& operator=(cbs::Prefab const&);
	private:
		GAME_IMPORT cbs::pcid_t AssignPrefabComponentId();
		GAME_IMPORT void ClearSerializationHierarchy();
	public:
		GAME_IMPORT cbs::PrefabMessagePipeSet const& GetPrefabMessagePipeSet() const;
		GAME_IMPORT void AddPropertyBinding(cbs::pcid_t, ttl::string_const<char>, cbs::pcid_t, ttl::string_const<char>);
		GAME_IMPORT void SetIgnorePresetClassNameValidation(bool);
		GAME_IMPORT ttl::string_base<char> GetLoggedName() const;
		GAME_IMPORT void RemovePropertyBinding(cbs::pcid_t, ttl::string_const<char>, cbs::pcid_t, ttl::string_const<char>);
		GAME_IMPORT cbs::Prefab const* GetContainerPrefab() const;
	private:
		GAME_IMPORT void CreateFieldsForInterface(CRTTI const*);
	public:
		GAME_IMPORT static ttl::string_base<char> GetWorkCopyPrefabName(char const*);
	private:
		GAME_IMPORT void SaveComponents(dom::IWriter&) const;
		GAME_IMPORT bool ParseInterface(dom::IReader::Value const&);
	public:
		GAME_IMPORT bool IsPartOfBindingScript(cbs::PropertyBinding const&) const;
	private:
		GAME_IMPORT bool ParseRuntimeData(dom::IReader::Value const&);
		GAME_IMPORT void SaveVirtualFields(dom::IWriter&) const;
		GAME_IMPORT guid PrepareGuid(SpawnContext&) const;
		GAME_IMPORT void ApplyDataPresets(cbs::CEntity*, PresetId) const;
		GAME_IMPORT void ClearInterface();
	public:
		GAME_IMPORT bool ImplementsPrefabInterface(rtti::Type const&) const;
		GAME_IMPORT bool CreateFromBuffer(char const*);
	private:
		GAME_IMPORT bool LinkInterfaceVirtualFieldsToEntity(cbs::PrefabInterfaceInfo const&, cbs::EntityInterface&, cbs::CEntity const*) const;
		GAME_IMPORT void ProcessForcedCoHierarchy(cbs::CEntity*, SpawnContext const&) const;
	public:
		GAME_IMPORT bool IsPartOfBindingScript(cbs::PipeBinding const&) const;
	private:
		GAME_IMPORT void SaveInterface(dom::IWriter&) const;
	public:
		GAME_IMPORT bool IsStreamingRoot() const;
		GAME_IMPORT Prefab(ClassReaderResolve const&);
		GAME_IMPORT ttl::string_base<char> const& GetContainerPrefabName() const;
	private:
		GAME_IMPORT void ResolvePropertyIsPartOfBindingScript(cbs::PropertyBinding const&) const;
	public:
		GAME_IMPORT void Preprocess(bool);
	private:
		GAME_IMPORT void ClearComponents();
	public:
		GAME_IMPORT cbs::PrefabPropertySet const& GetPrefabPropertySet() const;
	private:
		GAME_IMPORT bool ParseData(dom::IReader::Value const&);
		GAME_IMPORT bool LoadFromBuffer(char const*, uint32_t, bool);
		GAME_IMPORT bool LinkInterfaceMessagePipesToEntity(cbs::PrefabInterfaceInfo const&, cbs::EntityInterface&, cbs::CEntity const*) const;
		GAME_IMPORT PresetId ObtainPresetID(guid, SpawnContext const&) const;
	public:
		GAME_IMPORT static ttl::string_base<char> GetOriginalPrefabFileName(char const*);
		GAME_IMPORT bool GetEditorOnly() const;
		GAME_IMPORT cbs::Prefab::SPrefabEditorData& EditorData();
	private:
		GAME_IMPORT void CreateEntityComponents(cbs::CEntity*, SpawnContext const&, CPtrResolverDeferred&, int&) const;
		GAME_IMPORT void SetEntityData(cbs::CEntity*, SpawnContext const&, CPtrResolverDeferred&, PrefabResolveContext&) const;
	public:
		GAME_IMPORT ttl::string_base<char> GetContainerPrefabScriptName() const;
	private:
		GAME_IMPORT void ConnectComponents(PrefabResolveContext const&) const;
		GAME_IMPORT void InitializeEntity(cbs::CEntity*, SpawnContext const&) const;
	public:
		GAME_IMPORT void GetScriptName(ttl::temp_string_base<char, 240>&) const;
	private:
		GAME_IMPORT void ClearBindings();
		GAME_IMPORT bool ParseBindings(dom::IReader::Value const&);
	public:
		GAME_IMPORT bool CheckPrefabComponentPcids(ttl::string_base<char>&) const;
	private:
		GAME_IMPORT void Delete();
	public:
		GAME_IMPORT void SetDirty();
	private:
		GAME_IMPORT void PreprocessPrefabInterfaceMessagePipes();
	public:
		GAME_IMPORT void SetFromRpackCompact();
		GAME_IMPORT static ttl::string_base<char> RemovePrefabExtensions(ttl::string_base<char> const&);
	private:
		GAME_IMPORT void Clear();
	public:
		GAME_IMPORT void SetFromRpackLoose();
		GAME_IMPORT cbs::PrefabXformComponent const* GetRootXformComponent() const;
	private:
		GAME_IMPORT void PreprocessConvertUserColor();
		GAME_IMPORT void PreprocessVirtualFields();
	public:
		GAME_IMPORT cbs::PrefabEntityComponent const* FindPrefabEntityComponent(char const*) const;
		GAME_IMPORT bool CreateFromBuffer(char const*, uint32_t);
		GAME_IMPORT bool IsPcidForbiddenInThisGameMode(cbs::pcid_t const&) const;
	private:
		GAME_IMPORT bool ParseVirtualFields(dom::IReader::Value const&);
		GAME_IMPORT void ConnectComponentPipes(PrefabResolveContext const&) const;
	public:
		GAME_IMPORT cbs::CEntity* Spawn(SpawnContext&) const;
	private:
		GAME_IMPORT void ConnectComponentPipes(PrefabResolveContext const&, int) const;
	public:
		GAME_IMPORT ttl::vector<cbs::PropertyBinding, ttl::vector_allocators::heap_allocator<cbs::PropertyBinding>, 0> const& GetPropertyBinding() const;
	private:
		GAME_IMPORT void ConnectComponentProperties(PrefabResolveContext const&, int) const;
		GAME_IMPORT int GenerateEnityVariantHash(ttl::vector<uint32_t, ttl::vector_allocators::heap_allocator<uint32_t>, 2> const&) const;
	public:
		GAME_IMPORT cbs::Prefab::SPrefabEditorData const& GetEditorData() const;
		GAME_IMPORT static ttl::string_base<char> GetWorkCopyPrefabFileName(char const*);
	private:
		GAME_IMPORT bool ParseVirtualFieldDestinations(dom::IReader::Value const&, cbs::Prefab::SVirtualField&);
	public:
		GAME_IMPORT cbs::PrefabEntityComponent const* FindPrefabEntityComponent(cbs::CPcidPathView) const;
		GAME_IMPORT cbs::PrefabElement const* FindComponent(rtti::Type const&) const;
	private:
		GAME_IMPORT bool LinkInterfacePropertiesToEntity(cbs::PrefabInterfaceInfo const&, cbs::EntityInterface&, cbs::CEntity const*) const;
	public:
		GAME_IMPORT void RemovePipeBinding(cbs::pcid_t, ttl::string_const<char>, cbs::pcid_t, ttl::string_const<char>);
	private:
		GAME_IMPORT void ConnectComponentProperties(PrefabResolveContext const&) const;
		GAME_IMPORT void PreprocessComponentsAvailability();
	public:
		GAME_IMPORT Prefab(cbs::Prefab const&);
	private:
		GAME_IMPORT void SaveComponentsAndGlobalProperties(dom::IWriter&) const;
	public:
		GAME_IMPORT ttl::string_base<char> GetScriptName() const;
	private:
		GAME_IMPORT void ValidateInitStringOfEntityInterfaceField(ttl::string_const<char>, ttl::string_base<char>&) const;
		GAME_IMPORT cbs::CEntity* CreateEntityObject(SpawnContext const&) const;
	public:
		GAME_IMPORT cbs::PrefabEntityComponent const* FindPrefabEntityComponentByPrefabName(char const*) const;
		GAME_IMPORT bool LinkInterfaceToEntity(cbs::EntityInterface&, cbs::CEntity const*) const;
	private:
		GAME_IMPORT void CreateMessagePipeFieldForInterface(CRTTIFieldPIMessagePipe const*);
		GAME_IMPORT void SaveBindings(dom::IWriter&) const;
	public:
		GAME_IMPORT void Save(dom::IWriter&, void*, cbs::Prefab::ESavePrefabHierarchy) const;
	private:
		GAME_IMPORT bool ParsePrefabInterfaces(dom::IReader::Value const&);
		GAME_IMPORT ttl::string_base<char> GetDefaultPropertyValue(CRTTI const*, CRTTIFieldPIProperty const*);
	public:
		GAME_IMPORT bool SupportsAttaching() const;
	private:
		GAME_IMPORT bool ParseComponents(dom::IReader::Value const&);
	public:
		GAME_IMPORT ttl::vector<cbs::Prefab::SVirtualField, ttl::vector_allocators::heap_allocator<cbs::Prefab::SVirtualField>, 0> const& GetRawVirtualFields() const;
		GAME_IMPORT void SaveData(dom::IWriter&, void*) const;
		GAME_IMPORT bool IsFromRpackCompact() const;
	private:
		GAME_IMPORT void CreatePropertyFieldForInterface(CRTTI const*, CRTTIFieldPIProperty const*);
	public:
		GAME_IMPORT cbs::CEntity* CreateEntity(SpawnContext&) const;
	private:
		GAME_IMPORT void SavePrefabInterfaces(dom::IWriter&) const;
	public:
		GAME_IMPORT static ttl::string_base<char> RemovePrefabExtensions(ttl::string_base<char>&&);
	private:
		GAME_IMPORT void SetEntityRootXform(cbs::CEntity*, SpawnContext const&) const;
	public:
		GAME_IMPORT bool IsFromRpackLoose() const;
		GAME_IMPORT void RemovePrefabComponents(ttl::vector<cbs::PrefabElement*, ttl::vector_allocators::heap_allocator<cbs::PrefabElement*>, 1> const&, bool);
	protected:
		GAME_IMPORT Prefab(ttl::string_const<char>);
	public:
		GAME_IMPORT ttl::string_base<char> SaveToString(dom::EFormat::TYPE, cbs::Prefab::ESavePrefabHierarchy) const;
	private:
		GAME_IMPORT static cbs::Prefab* LoadFromFile(ttl::string_const<char>);
	public:
		GAME_IMPORT bool IsDefaultPlaceholder() const;
	private:
		GAME_IMPORT void SavePropertyBindings(dom::IWriter&) const;
	public:
		GAME_IMPORT ttl::vector<cbs::PipeBinding, ttl::vector_allocators::heap_allocator<cbs::PipeBinding>, 0> const& GetPipeBinding() const;
	private:
		GAME_IMPORT void CreateVirtualFields();
	public:
		GAME_IMPORT void SetEditorOnly(bool);
		GAME_IMPORT bool HasIgnorePresetClassNameValidation() const;
		GAME_IMPORT static ttl::string_base<char> GetCleanPrefabName(char const*);
		GAME_IMPORT void AddPipeBinding(cbs::pcid_t, ttl::string_const<char>, cbs::pcid_t, ttl::string_const<char>);
	private:
		GAME_IMPORT void PreprocessPrefabInterfaceProperties();
		GAME_IMPORT void ResolveBindingScript(cbs::CPointer<cbs::CEntity>, SpawnContext const&) const;
#pragma endregion
	};

	class PrefabManager {
#pragma region GENERATED by ExportClassToCPPH.py
	public:
		GAME_IMPORT static bool s_EnablePrefabsInRpacks;

		GAME_IMPORT void GetPrefabsNames(ttl::vector<ttl::string_base<char>, ttl::vector_allocators::heap_allocator<ttl::string_base<char>>, 1>&) const;
		GAME_IMPORT void SetIsGameInEditorMode(bool);
		GAME_IMPORT bool LogPrefabUsage(cbs::Prefab const*);
		GAME_IMPORT bool GetLoadEditorSpecificPrefabs() const;
	private:
		GAME_IMPORT void RemoveEmptyEntities(cbs::Prefab*);
	public:
		GAME_IMPORT bool ReleasePrefabPreloadedFromRpack(cbs::Prefab*);
		GAME_IMPORT bool GetIsGameInEditorMode();
		GAME_IMPORT cbs::Prefab* LoadPrefab(ttl::string_const<char>, char const*, uint32_t, bool*);
		GAME_IMPORT static cbs::PrefabElement* CreatePrefabElement(CRTTI const*);
	private:
		GAME_IMPORT void LoadTags();
	public:
		GAME_IMPORT cbs::Prefab* ReloadPrefab(cbs::Prefab* const, char const*, uint32_t);
	private:
		GAME_IMPORT void LoadPrefabPost(cbs::Prefab*);
	public:
		GAME_IMPORT void SavePrefab(cbs::Prefab const*, ttl::string_const<char>) const;
		GAME_IMPORT bool IsPrefabSpawned(cbs::Prefab const*) const;
		GAME_IMPORT void Dump() const;
	private:
		GAME_IMPORT void TestValidateBinaryPrefabs();
	public:
		GAME_IMPORT void PrefabFromRpackHandleStreamingRoot(cbs::Prefab*, bool);
		GAME_IMPORT bool ReleasePrefabPreloadedFromRpack(ttl::string_const<char>);
		GAME_IMPORT void LoadAllConfigs();
		GAME_IMPORT static cbs::PrefabElement* CreatePrefabElementBasedOnTargetRtti(rtti::Type const*);
		GAME_IMPORT uint64_t GetTags(ttl::string_const<char>, ttl::string_const<char>) const;
		GAME_IMPORT static cbs::PrefabComponent* CreatePrefabComponentBasedOnTargetRtti(rtti::Type const*);
		GAME_IMPORT void ReleasePrefab(cbs::Prefab*);
	private:
		GAME_IMPORT void Release();
	public:
		GAME_IMPORT cbs::Prefab* LoadTextPrefab(ttl::string_const<char>, char const*);
	private:
		GAME_IMPORT void UnregisterPrefab(ttl::string_const<char>);
	public:
		GAME_IMPORT void SetLoadEditorSpecificPrefabs(bool);
		GAME_IMPORT char const* GetPrefabTagsScript() const;
		GAME_IMPORT void SetTags(ttl::string_const<char>, ttl::string_const<char>, uint32_t64_t);
		GAME_IMPORT static void SanitizePrefabName(ttl::string_base<char>&);
		GAME_IMPORT cbs::Prefab* PreloadPrefabFromRpack(ttl::string_const<char>, char const*, uint32_t);
	private:
		GAME_IMPORT void LoadDefaultPrefab();
	public:
		GAME_IMPORT cbs::Prefab* FindPrefab(ttl::string_const<char>) const;
	private:
		GAME_IMPORT void RegisterPrefab(cbs::Prefab*);
		GAME_IMPORT cbs::Prefab* LoadPrefabFromFile(ttl::string_const<char>, bool*);
	public:
		GAME_IMPORT void ReleasePrefabsFromFolder(ttl::string_const<char>);
		GAME_IMPORT void ReleaseCityBuilderGenericPrefabs(ttl::string_const<char>);
		GAME_IMPORT static ttl::string_base<char> GetPrefabNameFromClass(CRTTI const*);
		GAME_IMPORT void PrefabFromRpackHandleSetStreamingRoot(cbs::Prefab*);
		GAME_IMPORT void SetVcsCheckFileAccessCallback(bool (*)(ttl::vector<ttl::string_base<char>, ttl::vector_allocators::heap_allocator<ttl::string_base<char>>, 1> const&));
		GAME_IMPORT std::unique_ptr<cbs::PrefabReloadMemento, std::default_delete<cbs::PrefabReloadMemento>> BeginPrefabReload(cbs::Prefab*);
		GAME_IMPORT void OverrideInGameFlagForOfflineProcessing(bool);
		GAME_IMPORT static cbs::PrefabElement* CreatePrefabElementBasedOnTargetRtti(CRTTI const*);
		GAME_IMPORT PrefabManager();
		GAME_IMPORT void Initialize();
		GAME_IMPORT void DumpEntities() const;
		GAME_IMPORT ttl::pair<cbs::Prefab*, bool> FindPrefabByNormalizedName(ttl::string_const<char>) const;
		GAME_IMPORT static cbs::PrefabElement* CreatePrefabElement(rtti::Type const*);
	private:
		GAME_IMPORT static uint32_t64_t HashPrefabName(ttl::string_const<char>);
	public:
		GAME_IMPORT void GetPrefabs(ttl::vector<cbs::Prefab*, ttl::vector_allocators::heap_allocator<cbs::Prefab*>, 1>&) const;
		GAME_IMPORT static cbs::PrefabComponent* CreatePrefabComponentBasedOnTargetRtti(CRTTI const*);
		GAME_IMPORT cbs::Prefab* GetPrefab(ttl::string_const<char>, bool, bool*);
		GAME_IMPORT void ReloadPrefabInPlace(cbs::Prefab&, char const*, uint32_t);
	private:
		GAME_IMPORT void TestValidateBinaryPresets();
		GAME_IMPORT void RegisterPrefab(ttl::string_const<char>, cbs::Prefab*);
	public:
		GAME_IMPORT void FinishPrefabReload(cbs::Prefab*, cbs::Prefab*, std::unique_ptr<cbs::PrefabReloadMemento, std::default_delete<cbs::PrefabReloadMemento>>);
#pragma endregion
	};

#pragma region GENERATED by ExportClassToCPPH.py
	public:
		GAME_IMPORT cbs::PrefabManager* g_PrefabManager;

		GAME_IMPORT void GetPECHierarchyPath(ttl::span<cbs::PrefabEntityComponent const* const, 4294967295>, uint32_t, ttl::string_base<char>&);
		GAME_IMPORT cbs::CPcidPath operator+(cbs::CPcidPathView, cbs::CPcidPathView);
		GAME_IMPORT void GatherSubtypeEntityInterfaces(ttl::set<CRTTI const*, ttl::less<CRTTI const*>, ttl::allocator>&, CRTTIField const*);
		GAME_IMPORT bool CreateEntityFromPrefabDeferred(cbs::CPointer<cbs::CEntity>&, ttl::string_const<char>, ILevel*, mtx34 const&, PresetId, Replication::CreateObjectOptions, bool);
		GAME_IMPORT cbs::CPcidPath operator+(cbs::CPcidPath& &, cbs::CPcidPath const&);
		GAME_IMPORT bool operator!=(cbs::CPointer<cbs::CEntity>, cbs::CEntityPointer);
		GAME_IMPORT cbs::CPcidPath operator+(cbs::CPcidPath const&, cbs::CPcidPathView);
		GAME_IMPORT void GetEntityDebugHierarchyPath(cbs::CEntity const*, ttl::string_base<char>&);
		GAME_IMPORT cbs::ComponentsPool& GetComponentsPool();
		GAME_IMPORT CLevel* GetCLevel(cbs::WorldIndex);
		GAME_IMPORT bool IsAnyAncestorAlwaysSpawned(cbs::CPointer<cbs::CEntity>);
		GAME_IMPORT void GetPCIDHierarchyPath(ttl::span<cbs::PrefabEntityComponent const* const, 4294967295>, uint32_t, ttl::string_base<char>&);
		GAME_IMPORT bool operator!=(cbs::CEntity const*, cbs::CEntityPointer);
		GAME_IMPORT ILevel* GetILevel(cbs::WorldIndex);
		GAME_IMPORT bool operator==(cbs::CPointer<cbs::CEntity>, cbs::CEntityPointer);
		GAME_IMPORT cbs::CPcidPath operator+(cbs::CPcidPathView, cbs::CPcidPath const&);
		GAME_IMPORT IPhysicsManager* GetPhysicsManager(cbs::WorldIndex);
		GAME_IMPORT bool GetPrefabEntityComponents(cbs::CEntity const*, ttl::vector<cbs::PrefabEntityComponent const*, ttl::vector_allocators::heap_allocator<cbs::PrefabEntityComponent const*>, 16>&);
		GAME_IMPORT cbs::EntitySpawnOrigin GetEntitySpawnOrigin(cbs::CEntity const*);
		GAME_IMPORT cbs::PrefabManager& GetPrefabManager();
		GAME_IMPORT float GetTimeDelta(cbs::WorldIndex);
		GAME_IMPORT ttl::string_base<char> GetEntityDebugInfoString(cbs::CEntity const*);
		GAME_IMPORT cbs::CPointer<cbs::CEntity> CreateEntityFromPrefab(ttl::string_const<char>, ILevel*, mtx34 const&, ttl::string_const<char>, Replication::CreateObjectOptions, bool, bool);
		GAME_IMPORT cbs::CPcidPath operator+(cbs::pcid_t, cbs::CPcidPath const&);
		GAME_IMPORT cbs::EntitySpawnOrigin GetEntitySpawnOrigin(cbs::PrefabEntityComponent const*);
		GAME_IMPORT cbs::CPcidPath operator+(cbs::CPcidPath const&, cbs::pcid_t);
		GAME_IMPORT ttl::string_base<char> GetSpawnContextDebugInfoString(SpawnContext const&);
		GAME_IMPORT bool operator<(cbs::CPcidPath const&, cbs::CPcidPath const&);
		GAME_IMPORT bool CreateEntityFromPrefabDeferred(cbs::CPointer<cbs::CEntity>&, ttl::string_const<char>, ILevel*, mtx34 const&, ttl::string_const<char>, Replication::CreateObjectOptions, bool, bool);
		GAME_IMPORT cbs::CPointer<cbs::CEntity> CreateEntityFromPrefab(ttl::string_const<char>, ILevel*, mtx34 const&, PresetId, Replication::CreateObjectOptions, bool);
		GAME_IMPORT bool operator==(cbs::CEntity const*, cbs::CEntityPointer);
		GAME_IMPORT bool IsInDynamicRoot(cbs::CPointer<cbs::CEntity>, bool);
		GAME_IMPORT cbs::CPcidPath operator+(cbs::CPcidPath const&, cbs::CPcidPath const&);
		GAME_IMPORT float GetTime(cbs::WorldIndex);
		GAME_IMPORT cbs::CPointer<cbs::CEntity> CreateEntityFromPrefab(ttl::string_const<char>, SpawnContext&);
		GAME_IMPORT bool operator==(cbs::CPcidPath const&, cbs::CPcidPath const&);
		GAME_IMPORT cbs::EnumPropertyManager& GetEnumPropertyManager();
		GAME_IMPORT bool CreateEntityFromPrefabDeferred(cbs::CPointer<cbs::CEntity>&, ttl::string_const<char>, SpawnContext&);
#pragma endregion
};