#pragma once
#include <EGSDK\vec3.h>
#include <EGSDK\Engine\IPhysicsCharacter.h>
#include <EGSDK\ClassHelpers.h>

namespace EGSDK::Engine {
	class EGameSDK_API CBulletPhysicsCharacter : IPhysicsCharacter {
#pragma region GENERATED by ExportClassToCPPH.py
	public:
		VIRTUAL_CALL(0, uint64_t*, sub_D0BDB0, (char a1), a1);
		VIRTUAL_CALL(1, int64_t, sub_E4E2B0, (int64_t a1, int64_t a2, int64_t a3), a1, a2, a3);
		VIRTUAL_CALL(2, int64_t, sub_E3EAA0, ());
		VIRTUAL_CALL(3, int64_t, sub_D5BF50, ());
		VIRTUAL_CALL(4, int64_t, _sub_D5BF501, ());
		VIRTUAL_CALL(5, CLevel const*, ToCLevel, ());
		VIRTUAL_CALL(6, int64_t, sub_E64980, ());
		VIRTUAL_CALL(7, static int, min_verts_per_poly, ());
		VIRTUAL_CALL(8, bool, sub_D324A0, ());
		VIRTUAL_CALL(9, void, sub_E38BE0, (float* a1), a1);
		VIRTUAL_CALL(10, int64_t, sub_D5BF70, ());
		VIRTUAL_CALL(11, int64_t, sub_E75940, (float* a1), a1);
		VIRTUAL_CALL(12, uint64_t*, sub_E491E0, (uint64_t* a1, int64_t a2), a1, a2);
		VIRTUAL_CALL(13, int64_t, sub_D5FF20, ());
		VIRTUAL_CALL(14, int64_t, sub_D44210, ());
		VIRTUAL_CALL(15, int64_t, sub_D58490, ());
		VIRTUAL_CALL(16, int64_t, sub_D5C0C0, ());
		VIRTUAL_CALL(17, int64_t, sub_E48A60, (uint32_t a1), a1);
		GAME_IMPORT virtual ttl::string_base<char> const& SampleCustomString(float, ttl::string_base<char> const&) const;
		VIRTUAL_CALL(19, int64_t, sub_D293A0, ());
		VIRTUAL_CALL(20, bool, updateRttiParams, ());
		VIRTUAL_CALL(21, int64_t, sub_E31BC0, ());
		VIRTUAL_CALL(22, int64_t, sub_E2E5F0, ());
		VIRTUAL_CALL(23, void, SetPlatform, ());
		VIRTUAL_CALL(24, int64_t, sub_E572A0, (int64_t a1), a1);
		VIRTUAL_CALL(25, int64_t, sub_E567D0, ());
		VIRTUAL_CALL(26, int64_t, sub_E72480, ());
		VIRTUAL_CALL(27, uint64_t*, sub_E71A30, (float a1), a1);
		VIRTUAL_CALL(28, int64_t, sub_E712A0, (float a1), a1);
		VIRTUAL_CALL(29, int64_t, sub_E54A10, (int64_t a1), a1);
		VIRTUAL_CALL(30, int64_t, sub_21B530, ());
		VIRTUAL_CALL(31, int64_t, sub_D2D3C0, ());
		VIRTUAL_CALL(32, gui::IObject*, ToIObject, ());
		VIRTUAL_CALL(33, int64_t, sub_E52950, (char a1), a1);
		VIRTUAL_CALL(34, void, sub_E52700, (char a1), a1);
		VIRTUAL_CALL(35, bool, sub_D32EC0, ());
		VIRTUAL_CALL(36, void, _SetPlatform1, ());
		VIRTUAL_CALL(37, int64_t, sub_D5B270, ());
		VIRTUAL_CALL(38, int64_t, sub_D2AF10, (int64_t a1), a1);
		VIRTUAL_CALL(39, void, _SetPlatform2, ());
		VIRTUAL_CALL(40, int64_t, sub_D2E200, ());
		VIRTUAL_CALL(41, int64_t, sub_D19600, ());
		VIRTUAL_CALL(42, int64_t, sub_D56390, ());
		VIRTUAL_CALL(43, void, sub_E33F10, (__m128* a1, int64_t a2, __m128* a3), a1, a2, a3);
		VIRTUAL_CALL(44, int64_t, sub_D3F110, ());
		VIRTUAL_CALL(45, int64_t, sub_E3C5B0, ());
		VIRTUAL_CALL(46, void, sub_E423A0, ());
		VIRTUAL_CALL(47, char, sub_E68740, (uint64_t* a1), a1);
		VIRTUAL_CALL(48, void, sub_E75820, (char a1), a1);
		VIRTUAL_CALL(49, char, sub_E39970, (int a1), a1);
		VIRTUAL_CALL(50, void, sub_D24750, (char a1), a1);
		VIRTUAL_CALL(51, int64_t, sub_D24710, ());
		VIRTUAL_CALL(52, int64_t, _sub_D2D3C01, ());
		VIRTUAL_CALL(53, void, _SetPlatform3, ());
		VIRTUAL_CALL(54, static float, default_region_min_size, ());
		VIRTUAL_CALL(55, static bool, ValidateVec4, (IGSObject const*, vec4 const&), const*, const&);
		VIRTUAL_CALL(56, int64_t, sub_D554A0, ());
		VIRTUAL_CALL(57, float const&, GetStartFrameConstValue, (gui::CActionGraphInstance*), gui::CActionGraphInstance*);
		VIRTUAL_CALL(58, bool, sub_E4D520, (int64_t a1, int64_t a2), a1, a2);
		VIRTUAL_CALL(59, _OWORD*, sub_E33D60, (_OWORD* a1, int64_t a2), a1, a2);
		VIRTUAL_CALL(60, int64_t, sub_D2E160, ());
#pragma endregion
	public:
		union {
			DynamicField(CBulletPhysicsCharacter, vec3, playerPos);
			DynamicField(CBulletPhysicsCharacter, vec3, playerPos2);
			DynamicField(CBulletPhysicsCharacter, float, playerDownwardVelocity);
		};

		static vec3 posBeforeFreeze;

		void FreezeCharacter();
		void MoveCharacter(const vec3& pos);

		static CBulletPhysicsCharacter* Get();
	};
}