#pragma once
#include <EGSDK\ClassHelpers.h>

namespace EGSDK {
	namespace GamePH {
		class GameDI_PH;
	}

	namespace Engine {
		class CVideoSettings;
		class CLevel;

		class EGameSDK_API CGame {
#pragma region GENERATED by ExportClassToCPPH.py
		public:
			GAME_IMPORT static rtti::Type& m_RTTI;
			GAME_IMPORT static bool __INTERNAL_crtti_fields_initialized_field;

			VIRTUAL_CALL(0, int64_t, sub_7E9B40, (int64_t a1, unsigned __int8 a2), a1, a2);
			VIRTUAL_CALL(1, IObject*, sub_7DC7E0, (char a1), a1);
			GAME_IMPORT virtual CRTTI const* GetRTTI() const;
			VIRTUAL_CALL(3, int64_t, sub_800AA0, ());
			VIRTUAL_CALL(4, MED::SModelOutfitGroup const*, unassigned, ());
			VIRTUAL_CALL(5, MED::SModelOutfitGroup const*, _unassigned1, ());
		protected:
			VIRTUAL_CALL(6, gui::CPackage*, ToCPackage, ());
		public:
			VIRTUAL_CALL(7, gui::CPackage*, _ToCPackage1, ());
			VIRTUAL_CALL(8, int64_t, RunUnitTests, ());
			VIRTUAL_CALL(9, int64_t, _RunUnitTests1, ());
			GAME_IMPORT virtual void GetPrivateObjects(ttl::list<IGSObject*, ttl::allocator>*, bool, bool);
			GAME_IMPORT virtual void DestroyPrivateObjects();
			VIRTUAL_CALL(12, MED::SModelOutfitGroup const*, _unassigned2, ());
			GAME_IMPORT virtual void GetAllObjects(ttl::vector<IGSObject*, ttl::vector_allocators::heap_allocator<IGSObject*>, 1>&, bool);
			GAME_IMPORT virtual void GetAllObjects(ttl::set<CRTTIObject*, ttl::less<CRTTIObject*>, ttl::allocator>&, ttl::set<CRTTIObject*, ttl::less<CRTTIObject*>, ttl::allocator>&, bool, std::optional<ttl::function_ref<bool ( CRTTIObject* )>>);
			VIRTUAL_CALL(15, bool, updateRttiParams, ());
			VIRTUAL_CALL(16, void, SetPlatform, ());
			GAME_IMPORT virtual char const* GetString(char const*) const;
			VIRTUAL_CALL(18, int64_t, sub_17D7D0, ());
			VIRTUAL_CALL(19, char, sub_15DDB0, ());
			VIRTUAL_CALL(20, int64_t, sub_80A6F0, ());
			VIRTUAL_CALL(21, MED::SModelOutfitGroup const*, _unassigned3, ());
			VIRTUAL_CALL(22, void, _SetPlatform4, ());
			GAME_IMPORT virtual Uid const& GetUid() const;
			VIRTUAL_CALL(24, bool, _updateRttiParams1, ());
			VIRTUAL_CALL(25, bool, _updateRttiParams2, ());
			VIRTUAL_CALL(26, bool, _updateRttiParams3, ());
			VIRTUAL_CALL(27, bool, _updateRttiParams4, ());
			VIRTUAL_CALL(28, bool, _updateRttiParams5, ());
			VIRTUAL_CALL(29, bool, _updateRttiParams6, ());
			VIRTUAL_CALL(30, bool, _updateRttiParams7, ());
			VIRTUAL_CALL(31, bool, _updateRttiParams8, ());
			VIRTUAL_CALL(32, bool, _updateRttiParams9, ());
			GAME_IMPORT virtual void CallVoidMethod(char const*, ...);
			GAME_IMPORT virtual cbs::msg::IMessagePipeSet const& GetMessagePipeSet() const;
			VIRTUAL_CALL(35, int64_t, _RunUnitTests2, ());
			VIRTUAL_CALL(36, MED::SModelOutfitGroup const*, _unassigned4, ());
			VIRTUAL_CALL(37, MED::SModelOutfitGroup const*, _unassigned5, ());
			VIRTUAL_CALL(38, MED::SModelOutfitGroup const*, _unassigned6, ());
			VIRTUAL_CALL(39, MED::SModelOutfitGroup const*, _unassigned7, ());
			GAME_IMPORT virtual cbs::prop::IPropertySet const& GetPropertySet() const;
			VIRTUAL_CALL(41, void, _SetPlatform5, ());
			VIRTUAL_CALL(42, int64_t, _RunUnitTests3, ());
			GAME_IMPORT virtual bool LoadField(CRTTIField const*, unsigned char, fs::ifile&, IPtrResolver&, bool);
			GAME_IMPORT virtual void LoadFields(dom::IReader::Object const&, IPtrResolver&, bool, bool (* )(char const*, CRTTIObject* ));
			GAME_IMPORT virtual void LoadFields(ITextDeserializer&, IPtrResolver&, bool);
			GAME_IMPORT virtual void LoadFields(fs::ifile&, IPtrResolver&, bool);
			GAME_IMPORT virtual void SaveFields(dom::IWriter&, ERTTIFlags, bool) const;
			GAME_IMPORT virtual int ToBufferReplicated(char*, int);
			GAME_IMPORT virtual int FromBufferReplicated(char*, int);
			GAME_IMPORT virtual int GetBufferReplicatedDataSize();
			VIRTUAL_CALL(51, void, _SetPlatform6, ());
			VIRTUAL_CALL(52, char, sub_1816B0, (const CRTTIField* a1), a1);
			GAME_IMPORT virtual bool CopyFields(CRTTIObject const*, bool);
			GAME_IMPORT virtual bool CopyPointerFields(CRTTIObject const*);
			GAME_IMPORT virtual bool ExchangePointerFields(CRTTIObject*);
			VIRTUAL_CALL(56, int64_t, sub_7F8D70, (int a1), a1);
			VIRTUAL_CALL(57, int64_t, sub_7F8F70, (int64_t a1), a1);
			VIRTUAL_CALL(58, int64_t, _RunUnitTests4, ());
			GAME_IMPORT virtual SRttiNetPointer GetNetPointer() const;
			VIRTUAL_CALL(60, int64_t, _RunUnitTests5, ());
			GAME_IMPORT virtual ttl::string_base<char> GetDebugDescription() const;
			VIRTUAL_CALL(62, int64_t, sub_7E65C0, (_DWORD* a1), a1);
			VIRTUAL_CALL(63, int64_t, sub_7E92C0, ());
			VIRTUAL_CALL(64, int64_t, sub_8092F0, ());
			VIRTUAL_CALL(65, bool, _updateRttiParams10, ());
			VIRTUAL_CALL(66, static bool, ValidateVec4, (IGSObject const*, vec4 const&), const*, const&);
			VIRTUAL_CALL(67, int64_t, sub_806BC0, ());
			GAME_IMPORT virtual ttl::string_base<char> ValueToString(CRTTIObject* const&) const;
			VIRTUAL_CALL(69, char, sub_15DD80, ());
			VIRTUAL_CALL(70, void, sub_17D770, (CRTTIField* a1, bool a2), a1, a2);
			VIRTUAL_CALL(71, bool, _updateRttiParams11, ());
			GAME_IMPORT virtual bool OnFieldChanged2(CRTTIField const*, bool);
			VIRTUAL_CALL(73, int64_t, sub_173040, ());
			VIRTUAL_CALL(74, char const*, GetMethodName, ());
			VIRTUAL_CALL(75, uint64_t*, sub_8343A0, (int64_t a1), a1);
			VIRTUAL_CALL(76, bool, _updateRttiParams12, ());
			VIRTUAL_CALL(77, char, sub_81DA90, (int64_t a1), a1);
			VIRTUAL_CALL(78, bool, _updateRttiParams13, ());
			VIRTUAL_CALL(79, bool, sub_81DA10, ());
			VIRTUAL_CALL(80, int64_t, _RunUnitTests6, ());
			VIRTUAL_CALL(81, int64_t, _RunUnitTests7, ());
			VIRTUAL_CALL(82, void, _SetPlatform7, ());
			GAME_IMPORT virtual void Query(IBaseValidator&, ttl::vector<CRTTIObject*, ttl::vector_allocators::heap_allocator<CRTTIObject*>, 1>&) const;
			VIRTUAL_CALL(84, bool, sub_15DE90, ());
			GAME_IMPORT virtual bool SelectObjectEditor(bool);
			GAME_IMPORT virtual bool HideObjectEditor(bool);
			VIRTUAL_CALL(87, char, sub_15E050, ());
			VIRTUAL_CALL(88, static void, RegisterSTTI, (CRTTI*), CRTTI*);
			VIRTUAL_CALL(89, int64_t, sub_7ED0C0, (int64_t a1), a1);
			VIRTUAL_CALL(90, int64_t, sub_7F4540, ());
			VIRTUAL_CALL(91, void, sub_15FFC0, (int64_t a1, int a2), a1, a2);
			VIRTUAL_CALL(92, char, sub_815470, (int64_t a1, __int16 a2, uint32_t a3), a1, a2, a3);
			VIRTUAL_CALL(93, uint64_t*, sub_131260, (int64_t* a1, int a2, int a3, int64_t a4, CRTTI* a5), a1, a2, a3, a4, a5);
			VIRTUAL_CALL(94, int64_t, sub_833BD0, (int64_t a1), a1);
			VIRTUAL_CALL(95, int64_t, sub_7F0310, ());
			VIRTUAL_CALL(96, void, _SetPlatform8, ());
			VIRTUAL_CALL(97, int64_t, sub_822BC0, ());
			GAME_IMPORT virtual void InitializeObject(CGSObject*);
			VIRTUAL_CALL(99, int64_t, sub_80C420, (int64_t a1), a1);
			VIRTUAL_CALL(100, void, sub_7F0FE0, ());
			VIRTUAL_CALL(101, int64_t, sub_7E9230, (int64_t a1), a1);
			VIRTUAL_CALL(102, int64_t, sub_7E8D70, (int64_t a1), a1);
			VIRTUAL_CALL(103, int64_t, sub_7E91C0, ());
			VIRTUAL_CALL(104, int64_t, sub_7E9030, ());
			VIRTUAL_CALL(105, int64_t, sub_7F89A0, ());
			VIRTUAL_CALL(106, char, sub_7F97C0, (int64_t a1, uint64_t* a2, _DWORD* a3), a1, a2, a3);
			VIRTUAL_CALL(107, char, sub_8130B0, (int64_t a1), a1);
			VIRTUAL_CALL(108, char, sub_813020, (uint64_t* * a1), a1);
			VIRTUAL_CALL(109, uint64_t*, sub_806400, (uint64_t* a1), a1);
			VIRTUAL_CALL(110, int64_t, sub_831710, (int64_t a1), a1);
			VIRTUAL_CALL(111, int64_t, sub_8316D0, (int64_t a1), a1);
			VIRTUAL_CALL(112, void, sub_8261B0, (int64_t a1), a1);
			VIRTUAL_CALL(113, void, sub_8260E0, (_BYTE* a1), a1);
			VIRTUAL_CALL(114, uint32_t64_t, sub_834570, (char a1), a1);
			VIRTUAL_CALL(115, int64_t, sub_8341B0, (int64_t a1), a1);
			VIRTUAL_CALL(116, int64_t, sub_833F80, (int64_t a1, int64_t a2), a1, a2);
			VIRTUAL_CALL(117, uint64_t*, sub_800900, (uint64_t* a1), a1);
			VIRTUAL_CALL(118, uint64_t*, sub_802EE0, (uint64_t* a1), a1);
			VIRTUAL_CALL(119, int64_t, sub_834400, ());
			VIRTUAL_CALL(120, void, sub_8262B0, (_BYTE* a1), a1);
			VIRTUAL_CALL(121, int64_t, sub_831870, (int64_t a1), a1);
			VIRTUAL_CALL(122, int64_t, sub_7E92E0, ());
			VIRTUAL_CALL(123, int64_t, sub_7E93C0, ());
			VIRTUAL_CALL(124, int64_t, sub_7E9390, ());
			VIRTUAL_CALL(125, int64_t, sub_7E93F0, ());
			VIRTUAL_CALL(126, int64_t, sub_7E9340, ());
			VIRTUAL_CALL(127, int64_t, sub_7E93E0, ());
			VIRTUAL_CALL(128, int64_t, sub_7E9330, ());
			VIRTUAL_CALL(129, int64_t, sub_7E93D0, ());
			VIRTUAL_CALL(130, int64_t, sub_7E9320, ());
			VIRTUAL_CALL(131, int64_t, sub_7E92F0, ());
			VIRTUAL_CALL(132, int64_t, sub_7E92D0, ());
			VIRTUAL_CALL(133, int64_t, sub_7E93A0, ());
			VIRTUAL_CALL(134, int64_t, sub_7E9400, ());
			VIRTUAL_CALL(135, int64_t, sub_7E9410, ());
			VIRTUAL_CALL(136, int64_t, sub_7E9420, ());
			VIRTUAL_CALL(137, int64_t, sub_7E9350, ());
			VIRTUAL_CALL(138, int64_t, sub_7E9360, ());
			VIRTUAL_CALL(139, int64_t, sub_7E9380, ());
			VIRTUAL_CALL(140, int64_t, sub_7E9370, ());
			VIRTUAL_CALL(141, int64_t, sub_7E9300, ());
			VIRTUAL_CALL(142, int64_t, sub_7E9310, ());
			VIRTUAL_CALL(143, int64_t, sub_7E93B0, ());
			VIRTUAL_CALL(144, bool, sub_811980, ());
			VIRTUAL_CALL(145, uint64_t*, sub_7FE950, (uint64_t* a1), a1);
			VIRTUAL_CALL(146, errno_t, sub_7EA3E0, ());
			VIRTUAL_CALL(147, int64_t, sub_81DB20, ());
			VIRTUAL_CALL(148, void, sub_81DAF0, ());
			VIRTUAL_CALL(149, int64_t, sub_81DB60, ());
			VIRTUAL_CALL(150, _BOOL8, sub_80C750, (int64_t a1, int64_t a2, int64_t a3), a1, a2, a3);
			VIRTUAL_CALL(151, int64_t, sub_80C820, (int64_t a1, int a2, int64_t a3, int64_t a4, int64_t a5, int a6, int a7, int64_t a8), a1, a2, a3, a4, a5, a6, a7, a8);
			VIRTUAL_CALL(152, const char*, sub_802750, ());
			VIRTUAL_CALL(153, int64_t, sub_81D870, (int64_t a1), a1);
			VIRTUAL_CALL(154, int64_t, sub_83D020, ());
			VIRTUAL_CALL(155, int64_t, sub_81D7F0, ());
			VIRTUAL_CALL(156, void, sub_7DD710, (uint64_t* a1), a1);
			VIRTUAL_CALL(157, int64_t, sub_8295F0, (int64_t* a1), a1);
			VIRTUAL_CALL(158, void, sub_829650, (int64_t a1), a1);
			VIRTUAL_CALL(159, int64_t, sub_803060, ());
			VIRTUAL_CALL(160, void* *, sub_810F60, (int a1), a1);
			VIRTUAL_CALL(161, int64_t, sub_81A870, ());
			VIRTUAL_CALL(162, uint32_t64_t*, sub_7FF6E0, (uint32_t64_t* a1), a1);
			VIRTUAL_CALL(163, int64_t, sub_8121D0, ());
			VIRTUAL_CALL(164, double, sub_834890, (int64_t a1, int64_t a2), a1, a2);
			VIRTUAL_CALL(165, float, sub_806860, ());
			VIRTUAL_CALL(166, void, sub_806910, (_DWORD* a1, _DWORD* a2), a1, a2);
			VIRTUAL_CALL(167, static float, default_region_min_size, ());

		private:
			GAME_IMPORT static rtti::Type& __INTERNAL_type_factory();
		public:
			GAME_IMPORT void Benchmark_Start();
			GAME_IMPORT void UnloadDynamicPatchRpack(ttl::string_const<char>);
			GAME_IMPORT void SetBufferForModels(ttl::vector<ttl::string_base<char>, ttl::vector_allocators::heap_allocator<ttl::string_base<char>>, 1> const&);
			GAME_IMPORT void Benchmark_End();
			GAME_IMPORT ttl::string_base<char> ParseCmdLineValue(ttl::string_base<char> const&);
			GAME_IMPORT Performance::CBenchmarkSession* Benchmark_GetSession();
			GAME_IMPORT static rtti::Type& typeinfo();
			GAME_IMPORT void Benchmark_CreateSession();
			GAME_IMPORT bool IsLaunchedFromEditor() const;
			GAME_IMPORT void Benchmark_DestroySession();
		private:
			GAME_IMPORT static bool __INTERNAL_crtti_fields_initialized_function();
			GAME_IMPORT static CRTTI* __INTERNAL_crtti_factory();
		public:
			GAME_IMPORT static CRTTI* GetSTTI();
			GAME_IMPORT ChromeSpy::IDataCollector* GetDataCollector() const;
			GAME_IMPORT bool LoadDynamicPatchRpack(ttl::string_const<char>);
#pragma endregion
		public:
			union {
				ClassHelpers::StaticBuffer<0x8, GamePH::GameDI_PH*> pGameDI_PH;
				ClassHelpers::StaticBuffer<0x28, CVideoSettings*> pCVideoSettings;
				DynamicField(CGame, CLevel*, pCLevel);
			};

			static CGame* Get();
		};
	}
}