#pragma once
#include <stdint.h>
#include <EGSDK\Exports.h>

namespace EGSDK::Engine {
	class EGameSDK_API CInput {
#pragma region GENERATED by ExportClassToCPPH.py
	public:
		VIRTUAL_CALL(0, void*, sub_AB9DC0, (char a1), a1);
		VIRTUAL_CALL(1, void, sub_ABA370, ());
		VIRTUAL_CALL(2, int64_t, sub_AE1710, ());
#pragma endregion
	public:
		void UnlockGameInput();
		uint64_t BlockGameInput();

		static CInput* Get();
	};
}