#pragma once
#include <EGSDK\ClassHelpers.h>

namespace EGSDK {
	namespace GamePH {
		class LevelDI;
	}

	namespace Engine {
		class CGSObject;

		class EGameSDK_API CLevel {
#pragma region GENERATED by ExportClassToCPPH.py
		public:
			GAME_IMPORT static char const* const CB_REGION_DIR_PREFIX;
			GAME_IMPORT static rtti::Type& m_RTTI;
			GAME_IMPORT static bool __INTERNAL_crtti_fields_initialized_field;
			GAME_IMPORT static char const* const GENERATED_CONTENT_DIR_NAME;

			VIRTUAL_CALL(0, int64_t, sub_7E9B40, (int64_t a1, unsigned __int8 a2), a1, a2);
			VIRTUAL_CALL(1, IObject*, sub_AFCDB0, (char a1), a1);
			GAME_IMPORT virtual CRTTI const* GetRTTI() const;
			VIRTUAL_CALL(3, int64_t, sub_B122A0, ());
			VIRTUAL_CALL(4, MED::SModelOutfitGroup const*, unassigned, ());
			VIRTUAL_CALL(5, MED::SModelOutfitGroup const*, _unassigned15, ());
		protected:
			VIRTUAL_CALL(6, gui::CPackage*, ToCPackage, ());
		public:
			VIRTUAL_CALL(7, gui::CPackage*, _ToCPackage3, ());
			VIRTUAL_CALL(8, int64_t, RunUnitTests, ());
			VIRTUAL_CALL(9, int64_t, _RunUnitTests15, ());
			GAME_IMPORT virtual void GetPrivateObjects(ttl::list<IGSObject*, ttl::allocator>*, bool, bool);
			GAME_IMPORT virtual void DestroyPrivateObjects();
			VIRTUAL_CALL(12, MED::SModelOutfitGroup const*, _unassigned16, ());
			GAME_IMPORT virtual void GetAllObjects(ttl::vector<IGSObject*, ttl::vector_allocators::heap_allocator<IGSObject*>, 1>&, bool);
			GAME_IMPORT virtual void GetAllObjects(ttl::set<CRTTIObject*, ttl::less<CRTTIObject*>, ttl::allocator>&, ttl::set<CRTTIObject*, ttl::less<CRTTIObject*>, ttl::allocator>&, bool, std::optional<ttl::function_ref<bool ( CRTTIObject* )>>);
			VIRTUAL_CALL(15, bool, updateRttiParams, ());
			VIRTUAL_CALL(16, void, SetPlatform, ());
			GAME_IMPORT virtual char const* GetString(char const*) const;
			VIRTUAL_CALL(18, int64_t, sub_17D7D0, ());
			VIRTUAL_CALL(19, char, sub_15DDB0, ());
			VIRTUAL_CALL(20, int64_t, sub_80A6F0, ());
			VIRTUAL_CALL(21, MED::SModelOutfitGroup const*, _unassigned17, ());
			VIRTUAL_CALL(22, void, _SetPlatform14, ());
			GAME_IMPORT virtual Uid const& GetUid() const;
			VIRTUAL_CALL(24, bool, _updateRttiParams27, ());
			VIRTUAL_CALL(25, bool, _updateRttiParams28, ());
			VIRTUAL_CALL(26, bool, _updateRttiParams29, ());
			VIRTUAL_CALL(27, bool, _updateRttiParams30, ());
			VIRTUAL_CALL(28, bool, _updateRttiParams31, ());
			VIRTUAL_CALL(29, bool, _updateRttiParams32, ());
			VIRTUAL_CALL(30, bool, _updateRttiParams33, ());
			VIRTUAL_CALL(31, bool, _updateRttiParams34, ());
			VIRTUAL_CALL(32, bool, _updateRttiParams35, ());
			GAME_IMPORT virtual void CallVoidMethod(char const*, ...);
			GAME_IMPORT virtual cbs::msg::IMessagePipeSet const& GetMessagePipeSet() const;
			VIRTUAL_CALL(35, int64_t, _RunUnitTests16, ());
			VIRTUAL_CALL(36, MED::SModelOutfitGroup const*, _unassigned18, ());
			VIRTUAL_CALL(37, MED::SModelOutfitGroup const*, _unassigned19, ());
			VIRTUAL_CALL(38, MED::SModelOutfitGroup const*, _unassigned20, ());
			VIRTUAL_CALL(39, MED::SModelOutfitGroup const*, _unassigned21, ());
			GAME_IMPORT virtual cbs::prop::IPropertySet const& GetPropertySet() const;
			VIRTUAL_CALL(41, void, _SetPlatform15, ());
			VIRTUAL_CALL(42, int64_t, _RunUnitTests17, ());
			GAME_IMPORT virtual bool LoadField(CRTTIField const*, unsigned char, fs::ifile&, IPtrResolver&, bool);
			GAME_IMPORT virtual void LoadFields(dom::IReader::Object const&, IPtrResolver&, bool, bool (* )(char const*, CRTTIObject* ));
			GAME_IMPORT virtual void LoadFields(ITextDeserializer&, IPtrResolver&, bool);
			GAME_IMPORT virtual void LoadFields(fs::ifile&, IPtrResolver&, bool);
			GAME_IMPORT virtual void SaveFields(dom::IWriter&, ERTTIFlags, bool) const;
			GAME_IMPORT virtual int ToBufferReplicated(char*, int);
			GAME_IMPORT virtual int FromBufferReplicated(char*, int);
			GAME_IMPORT virtual int GetBufferReplicatedDataSize();
			VIRTUAL_CALL(51, void, _SetPlatform16, ());
			VIRTUAL_CALL(52, char, sub_1816B0, (const CRTTIField* a1), a1);
			GAME_IMPORT virtual bool CopyFields(CRTTIObject const*, bool);
			GAME_IMPORT virtual bool CopyPointerFields(CRTTIObject const*);
			GAME_IMPORT virtual bool ExchangePointerFields(CRTTIObject*);
			VIRTUAL_CALL(56, int64_t, sub_7F8D70, (int a1), a1);
			VIRTUAL_CALL(57, int64_t, sub_7F8F70, (int64_t a1), a1);
			VIRTUAL_CALL(58, int64_t, _RunUnitTests18, ());
			GAME_IMPORT virtual SRttiNetPointer GetNetPointer() const;
			VIRTUAL_CALL(60, int64_t, _RunUnitTests19, ());
			GAME_IMPORT virtual ttl::string_base<char> GetDebugDescription() const;
			VIRTUAL_CALL(62, int64_t, sub_B005E0, (_DWORD* a1), a1);
			VIRTUAL_CALL(63, int64_t, sub_7E92C0, ());
			VIRTUAL_CALL(64, int64_t, sub_8092F0, ());
			VIRTUAL_CALL(65, bool, _updateRttiParams36, ());
			VIRTUAL_CALL(66, static bool, ValidateVec4, (IGSObject const*, vec4 const&), const*, const&);
			VIRTUAL_CALL(67, int64_t, sub_806BC0, ());
			GAME_IMPORT virtual ttl::string_base<char> ValueToString(CRTTIObject* const&) const;
			VIRTUAL_CALL(69, char, sub_15DD80, ());
			VIRTUAL_CALL(70, void, sub_17D770, (CRTTIField* a1, bool a2), a1, a2);
			VIRTUAL_CALL(71, bool, _updateRttiParams37, ());
			GAME_IMPORT virtual bool OnFieldChanged2(CRTTIField const*, bool);
			VIRTUAL_CALL(73, int64_t, sub_173040, ());
			VIRTUAL_CALL(74, char const*, GetMethodName, ());
			VIRTUAL_CALL(75, uint64_t*, sub_8343A0, (int64_t a1), a1);
			VIRTUAL_CALL(76, bool, _updateRttiParams38, ());
			VIRTUAL_CALL(77, char, sub_81DA90, (int64_t a1), a1);
			VIRTUAL_CALL(78, bool, _updateRttiParams39, ());
			VIRTUAL_CALL(79, bool, sub_81DA10, ());
			VIRTUAL_CALL(80, int64_t, _RunUnitTests20, ());
			VIRTUAL_CALL(81, int64_t, _RunUnitTests21, ());
			VIRTUAL_CALL(82, static void, RegisterSTTI, (CRTTI*), CRTTI*);
			GAME_IMPORT virtual void Query(IBaseValidator&, ttl::vector<CRTTIObject*, ttl::vector_allocators::heap_allocator<CRTTIObject*>, 1>&) const;
			VIRTUAL_CALL(84, bool, sub_15DE90, ());
			GAME_IMPORT virtual bool SelectObjectEditor(bool);
			GAME_IMPORT virtual bool HideObjectEditor(bool);
			VIRTUAL_CALL(87, char, sub_15E050, ());
			VIRTUAL_CALL(88, static void, _RegisterSTTI1, (CRTTI* a1), a1);
			VIRTUAL_CALL(89, int64_t, sub_7ED0C0, (int64_t a1), a1);
			VIRTUAL_CALL(90, int64_t, sub_7F4540, ());
			VIRTUAL_CALL(91, int64_t, sub_B1E130, (int64_t a1, uint32_t a2), a1, a2);
			VIRTUAL_CALL(92, char, sub_B1E1C0, (int64_t* a1, int64_t a2, uint32_t a3), a1, a2, a3);
			VIRTUAL_CALL(93, uint64_t*, sub_131260, (int64_t* a1, int a2, int a3, int64_t a4, CRTTI* a5), a1, a2, a3, a4, a5);
			VIRTUAL_CALL(94, void, sub_B30960, (gui::CActionNode* a1), a1);
			VIRTUAL_CALL(95, int64_t, sub_7F0310, ());
			VIRTUAL_CALL(96, int64_t, GsDriverEntry_0, ());
			VIRTUAL_CALL(97, void, _SetPlatform17, ());
			VIRTUAL_CALL(98, void, sub_B1C6E0, (CGSObject* a1), a1);
			VIRTUAL_CALL(99, int64_t, sub_80C420, (int64_t a1), a1);
			VIRTUAL_CALL(100, int, sub_B04E70, ());
			VIRTUAL_CALL(101, int64_t, sub_7E9230, (int64_t a1), a1);
			VIRTUAL_CALL(102, int64_t, sub_7E8D70, (int64_t a1), a1);
			VIRTUAL_CALL(103, int64_t, sub_7E91C0, ());
			VIRTUAL_CALL(104, int64_t, sub_B02400, ());
			VIRTUAL_CALL(105, int64_t, sub_7F89A0, ());
			VIRTUAL_CALL(106, char, sub_7F97C0, (int64_t a1, uint64_t* a2, _DWORD* a3), a1, a2, a3);
			VIRTUAL_CALL(107, char, sub_8130B0, (int64_t a1), a1);
			VIRTUAL_CALL(108, char, sub_813020, (uint64_t* * a1), a1);
			VIRTUAL_CALL(109, uint64_t*, sub_806400, (uint64_t* a1), a1);
			VIRTUAL_CALL(110, int64_t, sub_831710, (int64_t a1), a1);
			VIRTUAL_CALL(111, int64_t, sub_8316D0, (int64_t a1), a1);
			VIRTUAL_CALL(112, void, sub_8261B0, (int64_t a1), a1);
			VIRTUAL_CALL(113, void, sub_8260E0, (_BYTE* a1), a1);
			VIRTUAL_CALL(114, uint32_t64_t, sub_834570, (char a1), a1);
			VIRTUAL_CALL(115, int64_t, sub_8341B0, (int64_t a1), a1);
			VIRTUAL_CALL(116, int64_t, sub_833F80, (int64_t a1, int64_t a2), a1, a2);
			VIRTUAL_CALL(117, uint32_t64_t*, sub_B120A0, (uint32_t64_t* a1, char a2), a1, a2);
			VIRTUAL_CALL(118, uint64_t*, sub_802EE0, (uint64_t* a1), a1);
			VIRTUAL_CALL(119, int64_t, sub_834400, ());
			VIRTUAL_CALL(120, void, sub_8262B0, (_BYTE* a1), a1);
			VIRTUAL_CALL(121, int64_t, sub_831870, (int64_t a1), a1);
			VIRTUAL_CALL(122, int64_t, sub_7E92E0, ());
			VIRTUAL_CALL(123, int64_t, sub_7E93C0, ());
			VIRTUAL_CALL(124, int64_t, sub_7E9390, ());
			VIRTUAL_CALL(125, int64_t, sub_7E93F0, ());
			VIRTUAL_CALL(126, int64_t, sub_7E9340, ());
			VIRTUAL_CALL(127, int64_t, sub_7E93E0, ());
			VIRTUAL_CALL(128, int64_t, sub_7E9330, ());
			VIRTUAL_CALL(129, int64_t, sub_7E93D0, ());
			VIRTUAL_CALL(130, int64_t, sub_7E9320, ());
			VIRTUAL_CALL(131, int64_t, sub_7E92F0, ());
			VIRTUAL_CALL(132, int64_t, sub_7E92D0, ());
			VIRTUAL_CALL(133, int64_t, sub_7E93A0, ());
			VIRTUAL_CALL(134, int64_t, sub_7E9400, ());
			VIRTUAL_CALL(135, int64_t, sub_7E9410, ());
			VIRTUAL_CALL(136, int64_t, sub_7E9420, ());
			VIRTUAL_CALL(137, int64_t, sub_7E9350, ());
			VIRTUAL_CALL(138, int64_t, sub_7E9360, ());
			VIRTUAL_CALL(139, int64_t, sub_7E9380, ());
			VIRTUAL_CALL(140, int64_t, sub_7E9370, ());
			VIRTUAL_CALL(141, int64_t, sub_7E9300, ());
			VIRTUAL_CALL(142, int64_t, sub_7E9310, ());
			VIRTUAL_CALL(143, int64_t, sub_7E93B0, ());
			VIRTUAL_CALL(144, bool, sub_811980, ());
			VIRTUAL_CALL(145, uint64_t*, sub_7FE950, (uint64_t* a1), a1);
			VIRTUAL_CALL(146, int64_t, sub_B17A80, ());
			VIRTUAL_CALL(147, int64_t, _sub_B17A801, ());
			VIRTUAL_CALL(148, void, _SetPlatform18, ());
			VIRTUAL_CALL(149, void, _SetPlatform19, ());
			VIRTUAL_CALL(150, void, _SetPlatform20, ());
			VIRTUAL_CALL(151, void, _SetPlatform21, ());
			VIRTUAL_CALL(152, void, sub_B1D5B0, (uint64_t* a1), a1);
			VIRTUAL_CALL(153, int64_t, sub_B317B0, (uint64_t* a1), a1);
			VIRTUAL_CALL(154, const char*, sub_B17360, ());
			VIRTUAL_CALL(155, void, sub_B173B0, (MED::DebugPanel::Assets* a1), a1);
			VIRTUAL_CALL(156, int64_t, sub_B34690, ());
			VIRTUAL_CALL(157, int64_t, sub_B34990, ());
			VIRTUAL_CALL(158, int64_t, sub_B01150, (int64_t a1, float a2, float a3, float a4, int a5, int a6, char a7), a1, a2, a3, a4, a5, a6, a7);
			VIRTUAL_CALL(159, _DWORD*, sub_B31E40, (int* a1), a1);
			VIRTUAL_CALL(160, int64_t, sub_B17F00, (int64_t a1), a1);
			VIRTUAL_CALL(161, int64_t, sub_B22340, ());
			VIRTUAL_CALL(162, void, sub_B24B20, (int64_t a1), a1);
			VIRTUAL_CALL(163, int64_t, sub_AFCF70, ());
			VIRTUAL_CALL(164, int64_t, sub_B21770, (int64_t a1), a1);
			VIRTUAL_CALL(165, void, _SetPlatform22, ());
			VIRTUAL_CALL(166, int64_t, sub_B30870, (unsigned __int8 a1), a1);
			VIRTUAL_CALL(167, void, sub_B1A6E0, ());
			VIRTUAL_CALL(168, int64_t, sub_B05C30, ());
			VIRTUAL_CALL(169, void, _SetPlatform23, ());
			VIRTUAL_CALL(170, void, sub_B1A730, ());
			VIRTUAL_CALL(171, int64_t, sub_B1D370, ());
			VIRTUAL_CALL(172, void, sub_AFF1C0, (char a1), a1);
			VIRTUAL_CALL(173, int64_t, sub_B04C10, ());
			VIRTUAL_CALL(174, void, sub_B1A090, ());
			VIRTUAL_CALL(175, void*, sub_B1C680, ());
			VIRTUAL_CALL(176, int64_t, sub_B11210, ());
			VIRTUAL_CALL(177, int64_t, sub_B124D0, ());
			VIRTUAL_CALL(178, int64_t, sub_B12290, ());
			VIRTUAL_CALL(179, bool, sub_B1D230, ());
			VIRTUAL_CALL(180, int64_t, sub_B15DE0, ());
			VIRTUAL_CALL(181, void, sub_B31F30, (float a1), a1);
			VIRTUAL_CALL(182, float, sub_B183D0, ());
			VIRTUAL_CALL(183, int64_t, sub_B22310, (int64_t a1), a1);
			VIRTUAL_CALL(184, int64_t, sub_B22130, ());
			VIRTUAL_CALL(185, void, _SetPlatform24, ());
			VIRTUAL_CALL(186, char, sub_B2B0A0, (int64_t a1), a1);
			VIRTUAL_CALL(187, void, sub_B30B40, (uint32_t64_t a1), a1);
			VIRTUAL_CALL(188, void, sub_B30F90, (int64_t a1), a1);
			VIRTUAL_CALL(189, uint32_t64_t*, sub_B03FE0, (uint32_t64_t* a1, char* a2, ... a3), a1, a2, a3);
			VIRTUAL_CALL(190, int64_t, sub_B15200, (int a1), a1);
			VIRTUAL_CALL(191, uint32_t64_t*, sub_B13DC0, (uint32_t64_t* a1), a1);
			VIRTUAL_CALL(192, int64_t, sub_B144B0, (int64_t a1), a1);
			VIRTUAL_CALL(193, physics_spec_walk*, sub_B13DF0, (physics_spec_walk* a1), a1);
			VIRTUAL_CALL(194, int64_t, sub_B111F0, ());
			VIRTUAL_CALL(195, int64_t, sub_B22040, ());
			VIRTUAL_CALL(196, int64_t, sub_B220F0, ());
			VIRTUAL_CALL(197, _DWORD*, sub_B0C760, ());
			VIRTUAL_CALL(198, int64_t, sub_B0D030, ());
			VIRTUAL_CALL(199, int64_t, sub_B0D040, ());
			VIRTUAL_CALL(200, int64_t, sub_B221D0, ());
			VIRTUAL_CALL(201, void, sub_B222C0, ());
			VIRTUAL_CALL(202, uint64_t*, sub_B02D00, ());
			VIRTUAL_CALL(203, int64_t, sub_B28550, (char a1, int64_t a2, int64_t a3, SExtCollInfo* a4), a1, a2, a3, a4);
			VIRTUAL_CALL(204, bool, sub_B281E0, (char a1, int64_t a2, int64_t a3, int64_t a4), a1, a2, a3, a4);
			VIRTUAL_CALL(205, uint32_t, sub_B21210, (char a1, int64_t a2, int64_t a3, MED::SModelOutfitItems* a4, int64_t a5), a1, a2, a3, a4, a5);
			VIRTUAL_CALL(206, int64_t, sub_B07AE0, (char a1, uint32_t* a2, int64_t a3, int64_t a4, __int128* a5, char a6), a1, a2, a3, a4, a5, a6);
			VIRTUAL_CALL(207, void, sub_B07DD0, (char a1, int64_t a2, int64_t a3, int64_t a4, __int128* a5), a1, a2, a3, a4, a5);
			VIRTUAL_CALL(208, void, sub_AFD490, (int64_t a1, char a2), a1, a2);
			VIRTUAL_CALL(209, int64_t, sub_B2C870, (int64_t a1), a1);
			VIRTUAL_CALL(210, int64_t, sub_B2F0B0, (int64_t* a1), a1);
			VIRTUAL_CALL(211, int64_t, sub_B2ECF0, (int64_t a1), a1);
			VIRTUAL_CALL(212, uint32_t64_t*, sub_B16F10, (uint32_t64_t* a1), a1);
			VIRTUAL_CALL(213, void, _SetPlatform25, ());
			VIRTUAL_CALL(214, float, sub_B3EDC0, ());

			GAME_IMPORT ttl::vector<cbs::CPointer<cbs::CEntity>, ttl::vector_allocators::heap_allocator<cbs::CPointer<cbs::CEntity>>, 0> const& GetAlwaysSpawnedEntities() const;
			GAME_IMPORT ttl::string_base<char> GetLevelGeneratedContentRegionPath(ttl::string_base<char> const&) const;
			GAME_IMPORT IVarlistMixer* GetVarlistMixer() const;
			GAME_IMPORT ttl::string_base<char> GetLevelGeneratedContentRegionPath(int) const;
			GAME_IMPORT IVarlistStack* GetVarlistStack() const;
		private:
			GAME_IMPORT static bool __INTERNAL_crtti_fields_initialized_function();
		public:
			GAME_IMPORT static rtti::Type& typeinfo();
		private:
			GAME_IMPORT static rtti::Type& __INTERNAL_type_factory();
		public:
			GAME_IMPORT IAutoSoundEmitterMgr* GetAutoSoundEmitterManager();
			GAME_IMPORT void OnCameraPositionChangedOffline(CBaseCamera*);
		private:
			GAME_IMPORT static CRTTI* __INTERNAL_crtti_factory();
		public:
			GAME_IMPORT IVarlistManager* GetVarlistManager() const;
			GAME_IMPORT float GetCurrentDaytime() const;
			GAME_IMPORT CPostprocessBlendManager* GetPostprocessBlendManager() const;
			GAME_IMPORT ttl::string_base<char> GetLevelGeneratedContentPath() const;
			GAME_IMPORT static CRTTI* GetSTTI();
			GAME_IMPORT static char const* GetGeneratedContentDirName();
#pragma endregion
		public:
			union {
				ClassHelpers::StaticBuffer<0x20, GamePH::LevelDI*> pLevelDI;
				ClassHelpers::StaticBuffer<0x30, CGSObject*> pCGSObject;
			};

			static CLevel* Get();
		};
	}
}