#pragma once
#include <EGSDK\ClassHelpers.h>

namespace EGSDK::Engine {
	class CGame;

	class EGameSDK_API CLobbySteam {
#pragma region GENERATED by ExportClassToCPPH.py
	public:
		VIRTUAL_CALL(0, char*, sub_1333280, (char a1), a1);
		VIRTUAL_CALL(1, char, sub_1335710, ());
		VIRTUAL_CALL(2, int64_t, sub_1355D10, ());
		VIRTUAL_CALL(3, int64_t, sub_1396450, ());
		VIRTUAL_CALL(4, int64_t, sub_13966D0, ());
		VIRTUAL_CALL(5, int64_t, sub_13713F0, ());
		VIRTUAL_CALL(6, void, sub_13964C0, ());
		VIRTUAL_CALL(7, int64_t, sub_1340C80, ());
		VIRTUAL_CALL(8, int64_t, sub_1377430, (int64_t a1, int64_t a2), a1, a2);
		VIRTUAL_CALL(9, char, sub_1359CA0, (int64_t a1), a1);
		VIRTUAL_CALL(10, static bool, ValidateVec4, (IGSObject const*, vec4 const&), const*, const&);
		VIRTUAL_CALL(11, bool, updateRttiParams, ());
		VIRTUAL_CALL(12, void, SetPlatform, ());
		VIRTUAL_CALL(13, void, _SetPlatform26, ());
		VIRTUAL_CALL(14, void, _SetPlatform27, ());
		VIRTUAL_CALL(15, void, _SetPlatform28, ());
		VIRTUAL_CALL(16, void, sub_13851D0, ());
		VIRTUAL_CALL(17, float const&, GetzConstValue, (gui::CActionGraphInstance*), gui::CActionGraphInstance*);
		VIRTUAL_CALL(18, int64_t, sub_1359D10, ());
		VIRTUAL_CALL(19, int64_t, sub_1359C80, ());
		VIRTUAL_CALL(20, void, _SetPlatform29, ());
		VIRTUAL_CALL(21, bool, _updateRttiParams40, ());
		VIRTUAL_CALL(22, void, _SetPlatform30, ());
		VIRTUAL_CALL(23, void, _SetPlatform31, ());
		VIRTUAL_CALL(24, bool, _updateRttiParams41, ());
		VIRTUAL_CALL(25, int64_t, sub_13529A0, (int64_t a1), a1);
		VIRTUAL_CALL(26, void, _SetPlatform32, ());
		VIRTUAL_CALL(27, int64_t, sub_1388780, ());
		VIRTUAL_CALL(28, int64_t, sub_1388A50, ());
		VIRTUAL_CALL(29, void, _SetPlatform33, ());
		VIRTUAL_CALL(30, void, sub_1341F70, ());
		VIRTUAL_CALL(31, void* *, sub_13711B0, ());
		VIRTUAL_CALL(32, void, sub_1396770, ());
		VIRTUAL_CALL(33, bool, sub_1359CC0, ());
		VIRTUAL_CALL(34, bool, _updateRttiParams42, ());
		GAME_IMPORT virtual ttl::string_base<char> ValueToString(CRTTIObject* const&) const;
		VIRTUAL_CALL(36, int64_t, sub_1385F70, (uint32_t64_t* a1, int a2), a1, a2);
#pragma endregion
	public:
		union {
			ClassHelpers::StaticBuffer<0xF8, CGame*> pCGame;
		};

		static CLobbySteam* Get();
	};
}