#pragma once
#include <optional>
#include <functional>
#include <EGSDK\Imports.h>
#include <EGSDK\Engine\rtti.h>
#include <EGSDK\Engine\IObject.h>
#include <EGSDK\Engine\ttl\vector_allocators\heap_allocator.h>
#include <EGSDK\Engine\ttl\allocator.h>
#include <EGSDK\Engine\ttl\list.h>
#include <EGSDK\Engine\ttl\vector.h>
#include <EGSDK\Engine\ttl\set.h>
#include <EGSDK\Engine\ttl\less.h>
#include <EGSDK\Engine\Uid.h>

class IGSObject;
class MED {
public:
	struct SModelOutfitGroup;
};

class CRTTIObject {
#pragma region GENERATED by ExportClassToCPPH.py
	public:
		GAME_IMPORT static rtti::Type& m_RTTI;
		GAME_IMPORT static bool __INTERNAL_crtti_fields_initialized_field;

		VIRTUAL_CALL(0, void, SetPlatform, ());
		VIRTUAL_CALL(1, IObject*, sub_11DE70, (char a1), a1);
		GAME_IMPORT virtual CRTTI const* GetRTTI() const;
		VIRTUAL_CALL(3, CRTTI const*, _GetRTTI1, ());
		VIRTUAL_CALL(4, MED::SModelOutfitGroup const*, unassigned, ());
		VIRTUAL_CALL(5, MED::SModelOutfitGroup const*, _unassigned1, ());
		VIRTUAL_CALL(6, MED::SModelOutfitGroup const*, _unassigned2, ());
		VIRTUAL_CALL(7, MED::SModelOutfitGroup const*, _unassigned3, ());
		VIRTUAL_CALL(8, int64_t, RunUnitTests, ());
		VIRTUAL_CALL(9, int64_t, _RunUnitTests1, ());
		GAME_IMPORT virtual void GetPrivateObjects(ttl::list<IGSObject*, ttl::allocator>*, bool, bool);
		GAME_IMPORT virtual void DestroyPrivateObjects();
		VIRTUAL_CALL(12, int64_t, _RunUnitTests2, ());
		GAME_IMPORT virtual void GetAllObjects(ttl::vector<IGSObject*, ttl::vector_allocators::heap_allocator<IGSObject*>, 1>&, bool);
		GAME_IMPORT virtual void GetAllObjects(ttl::set<CRTTIObject*, ttl::less<CRTTIObject*>, ttl::allocator>&, ttl::set<CRTTIObject*, ttl::less<CRTTIObject*>, ttl::allocator>&, bool, std::optional<ttl::function_ref<bool ( CRTTIObject* )>>);
		VIRTUAL_CALL(15, bool, updateRttiParams, ());
		VIRTUAL_CALL(16, void, _SetPlatform1, ());
		GAME_IMPORT virtual char const* GetString(char const*) const;
		VIRTUAL_CALL(18, void, _SetPlatform2, ());
		VIRTUAL_CALL(19, static bool, ValidateVec4, (IGSObject const*, vec4 const&), const*, const&);
		VIRTUAL_CALL(20, void, _SetPlatform3, ());
		VIRTUAL_CALL(21, MED::SModelOutfitGroup const*, _unassigned4, ());
		VIRTUAL_CALL(22, void, _SetPlatform4, ());
		GAME_IMPORT virtual Uid const& GetUid() const;
		VIRTUAL_CALL(24, bool, _updateRttiParams1, ());
		VIRTUAL_CALL(25, bool, _updateRttiParams2, ());
		VIRTUAL_CALL(26, bool, _updateRttiParams3, ());
		VIRTUAL_CALL(27, bool, _updateRttiParams4, ());
		VIRTUAL_CALL(28, bool, _updateRttiParams5, ());
		VIRTUAL_CALL(29, bool, _updateRttiParams6, ());
		VIRTUAL_CALL(30, bool, _updateRttiParams7, ());
		VIRTUAL_CALL(31, bool, _updateRttiParams8, ());
		VIRTUAL_CALL(32, bool, _updateRttiParams9, ());
		GAME_IMPORT virtual void CallVoidMethod(char const*, ...);
		GAME_IMPORT virtual cbs::msg::IMessagePipeSet const& GetMessagePipeSet() const;
		VIRTUAL_CALL(35, int64_t, _RunUnitTests3, ());
		VIRTUAL_CALL(36, MED::SModelOutfitGroup const*, _unassigned5, ());
		VIRTUAL_CALL(37, MED::SModelOutfitGroup const*, _unassigned6, ());
		VIRTUAL_CALL(38, MED::SModelOutfitGroup const*, _unassigned7, ());
		VIRTUAL_CALL(39, MED::SModelOutfitGroup const*, _unassigned8, ());
		GAME_IMPORT virtual cbs::prop::IPropertySet const& GetPropertySet() const;
		VIRTUAL_CALL(41, void, _SetPlatform5, ());
		VIRTUAL_CALL(42, int64_t, _RunUnitTests4, ());
		GAME_IMPORT virtual bool LoadField(CRTTIField const*, unsigned char, fs::ifile&, IPtrResolver&, bool);
		GAME_IMPORT virtual void LoadFields(dom::IReader::Object const&, IPtrResolver&, bool, bool (* )(char const*, CRTTIObject* ));
		GAME_IMPORT virtual void LoadFields(ITextDeserializer&, IPtrResolver&, bool);
		GAME_IMPORT virtual void LoadFields(fs::ifile&, IPtrResolver&, bool);
		GAME_IMPORT virtual void SaveFields(dom::IWriter&, ERTTIFlags, bool) const;
		GAME_IMPORT virtual int ToBufferReplicated(char*, int);
		GAME_IMPORT virtual int FromBufferReplicated(char*, int);
		GAME_IMPORT virtual int GetBufferReplicatedDataSize();
		VIRTUAL_CALL(51, void, _SetPlatform6, ());
		VIRTUAL_CALL(52, static bool, _ValidateVec41, (IGSObject const* a1, vec4 const& a2), a1, a2);
		GAME_IMPORT virtual bool CopyFields(CRTTIObject const*, bool);
		GAME_IMPORT virtual bool CopyPointerFields(CRTTIObject const*);
		GAME_IMPORT virtual bool ExchangePointerFields(CRTTIObject*);
		VIRTUAL_CALL(56, int64_t, _RunUnitTests5, ());
		VIRTUAL_CALL(57, int64_t, _RunUnitTests6, ());
		VIRTUAL_CALL(58, int64_t, _RunUnitTests7, ());
		GAME_IMPORT virtual SRttiNetPointer GetNetPointer() const;
		VIRTUAL_CALL(60, int64_t, _RunUnitTests8, ());
		GAME_IMPORT virtual ttl::string_base<char> GetDebugDescription() const;
		GAME_IMPORT virtual void CalcMemoryUsage(SObjectMemoryUsage&) const;
		VIRTUAL_CALL(63, void, _SetPlatform7, ());
		GAME_IMPORT virtual bool GetValidFieldValuesEditor(CRTTIField const&, ttl::vector<ttl::string_base<char>, ttl::vector_allocators::heap_allocator<ttl::string_base<char>>, 1>&, ttl::vector<ttl::string_base<char>, ttl::vector_allocators::heap_allocator<ttl::string_base<char>>, 1>&);
		VIRTUAL_CALL(65, bool, _updateRttiParams10, ());
		VIRTUAL_CALL(66, static bool, _ValidateVec42, (IGSObject const* a1, vec4 const& a2), a1, a2);
		VIRTUAL_CALL(67, int64_t, _RunUnitTests9, ());
		GAME_IMPORT virtual ttl::string_base<char> ValueToString(CRTTIObject* const&) const;
		GAME_IMPORT virtual bool IsFieldChanged(CRTTIField const*) const;
		GAME_IMPORT virtual void SetFieldChangedFlag(CRTTIField const*, bool);
		VIRTUAL_CALL(71, bool, _updateRttiParams11, ());
		GAME_IMPORT virtual bool OnFieldChanged2(CRTTIField const*, bool);
		VIRTUAL_CALL(73, void, _SetPlatform8, ());
		VIRTUAL_CALL(74, int64_t, _RunUnitTests10, ());
		VIRTUAL_CALL(75, void, _SetPlatform9, ());
		VIRTUAL_CALL(76, bool, _updateRttiParams12, ());
	protected:
		GAME_IMPORT virtual bool OnFieldChanged(CRTTIField const*, bool);
	public:
		VIRTUAL_CALL(78, bool, _updateRttiParams13, ());
		VIRTUAL_CALL(79, bool, _updateRttiParams14, ());
		VIRTUAL_CALL(80, int64_t, _RunUnitTests11, ());
		VIRTUAL_CALL(81, int64_t, _RunUnitTests12, ());
		VIRTUAL_CALL(82, void, _SetPlatform10, ());
		GAME_IMPORT virtual void Query(IBaseValidator&, ttl::vector<CRTTIObject*, ttl::vector_allocators::heap_allocator<CRTTIObject*>, 1>&) const;

		GAME_IMPORT bool FromEngineClass(CRTTI const*) const;
	private:
		GAME_IMPORT static CRTTI* __INTERNAL_crtti_factory();
	public:
		GAME_IMPORT CRTTIField const* FindFieldDynamic(ttl::string_view_base<char, ttl::char_traits<char>>) const;
		GAME_IMPORT bool FromClassByName(char const*) const;
		GAME_IMPORT CRTTIFieldEmbeddedObject const* SetFieldEmbeddedObject(ttl::string_const<char>, CEmbeddedObject* const&);
		GAME_IMPORT bool FromClassOrInterfaceByName(char const*) const;
		GAME_IMPORT CRTTIMethod const* FindMethod(char const*) const;
		GAME_IMPORT CRTTIFieldTyped<unsigned short> const* SetFieldUShort(ttl::string_const<char>, unsigned short);
		GAME_IMPORT CRTTIFieldTyped<float> const* SetFieldFloat(ttl::string_const<char>, float);
		GAME_IMPORT bool FromClassOrInterface(int) const;
		GAME_IMPORT bool FromClass(rtti::Type const*) const;
	private:
		GAME_IMPORT static bool __INTERNAL_crtti_fields_initialized_function();
	public:
		GAME_IMPORT CRTTIFieldTyped<unsigned char> const* SetFieldUChar(ttl::string_const<char>, unsigned char);
		GAME_IMPORT bool IsExactClass(rtti::Type const*) const;
		GAME_IMPORT bool FromEngineClass(int) const;
		GAME_IMPORT bool FromClass(int) const;
		GAME_IMPORT void GetLocalFields(ttl::vector<CRTTIField const*, ttl::vector_allocators::heap_allocator<CRTTIField const*>, 64>&) const;
		GAME_IMPORT static CRTTIObject* LoadObjectHierarchy(fs::ifile&, bool, cbs::WorldIndex);
		GAME_IMPORT CRTTIFieldTyped<vec4> const* GetFieldVec4(ttl::string_const<char>, vec4&) const;
		GAME_IMPORT bool FromEngineClass(rtti::Type const&) const;
		GAME_IMPORT CRTTIFieldVectorTyped<vec4> const* GetFieldVec4Vector(ttl::string_const<char>, ttl::vector<vec4, ttl::vector_allocators::heap_allocator<vec4>, 0>&) const;
	private:
		GAME_IMPORT static rtti::Type& __INTERNAL_type_factory();
	public:
		GAME_IMPORT CRTTIFieldTyped<vec4> const* SetFieldVec4(ttl::string_const<char>, vec4 const&);
		GAME_IMPORT static rtti::Type& typeinfo();
		GAME_IMPORT static CRTTIObject* LoadObjectHierarchy(ITextDeserializer&, bool, cbs::WorldIndex);
		GAME_IMPORT bool FromClassOrInterface(rtti::Type const*) const;
		GAME_IMPORT static CRTTINative<CRTTIObject>* GetSTTI();
		GAME_IMPORT CRTTIField const* FindField(char const*) const;
		GAME_IMPORT bool FromClass(CRTTI const*) const;
		GAME_IMPORT bool IsExactEngineClass(int) const;
		GAME_IMPORT CRTTIFieldVectorTyped<vec4> const* SetFieldVec4Vector(ttl::string_const<char>, ttl::vector<vec4, ttl::vector_allocators::heap_allocator<vec4>, 0> const&);
		GAME_IMPORT char const* GetClassNameA() const;
		GAME_IMPORT bool IsExactClass(CRTTI const*) const;
		GAME_IMPORT CRTTIField const* FindFieldIncludingAliases(ttl::string_view_base<char, ttl::char_traits<char>>) const;
		GAME_IMPORT bool IsExactClass(int) const;
		GAME_IMPORT CRTTIField const* FindFieldIncludingAliases(char const*) const;
		GAME_IMPORT bool IsExactClassByName(char const*) const;
		GAME_IMPORT CRTTIObject();
		GAME_IMPORT CRTTIFieldString const* SetFieldString(ttl::string_const<char>, ttl::string_const<char>);
		GAME_IMPORT void GetAllLocalFields(ttl::vector<CRTTIField const*, ttl::vector_allocators::heap_allocator<CRTTIField const*>, 64>&) const;
		GAME_IMPORT CRTTIField const* FindField(ttl::string_view_base<char, ttl::char_traits<char>>) const;
		GAME_IMPORT CRTTIField const* FindFieldDynamic(char const*) const;
		GAME_IMPORT static void RegisterValidator(IBaseValidator&, CRTTI const&);
		GAME_IMPORT CRTTIFieldTyped<uint32_t> const* SetFieldUInt(ttl::string_const<char>, uint32_t);
		GAME_IMPORT ttl::temp_string_base<char, 240> GetClassNameWithoutNamespace() const;
		GAME_IMPORT bool FromClassOrInterface(CRTTI const*) const;
		GAME_IMPORT CEmbeddedObject* CreateRawEmbeddedObject(CRTTI const*, char const*, CRTTIObject*, CRTTIField const*) const;
#pragma endregion
};