#pragma once
#include <EGSDK\Imports.h>
#include <EGSDK\Engine\ClassReaderResolve.h>

class CRTTI;
class CRTTIMethod {
#pragma region GENERATED by ExportClassToCPPH.py
	public:
		VIRTUAL_CALL(0, uint64_t*, sub_11DDE0, (char a1), a1);
		virtual void _StrippedVFunc1() = 0;
		virtual void _StrippedVFunc2() = 0;
		virtual void _StrippedVFunc3() = 0;

		GAME_IMPORT char const* GetMethodClassName() const;
		GAME_IMPORT CRTTIMethod(CRTTI*, char const*);
		GAME_IMPORT void DecTimeHandlerRefcount();
		GAME_IMPORT CRTTIMethod(ClassReaderResolve const&);
		GAME_IMPORT CRTTIMethod(CRTTIMethod const&);
		GAME_IMPORT CRTTIMethod& operator=(CRTTIMethod const&);
#pragma endregion
};