#pragma once
#include <EGSDK\Imports.h>

class CRTTIField {
#pragma region GENERATED by ExportClassToCPPH.py
	public:
		VIRTUAL_CALL(0, CRTTIField*, sub_119B50, (char a1), a1);
		VIRTUAL_CALL(1, int64_t, RunUnitTests, ());
		GAME_IMPORT virtual CRTTIField::Variant* GetFieldDefaultVariantPtr(CRTTI const*) const;
		VIRTUAL_CALL(3, int64_t, _RunUnitTests1, ());
		virtual void _StrippedVFunc1() = 0;
		virtual void _StrippedVFunc2() = 0;
		virtual void _StrippedVFunc3() = 0;
		VIRTUAL_CALL(7, bool, updateRttiParams, ());
		GAME_IMPORT virtual bool GetValidValuesEditor(CRTTIObject*, ttl::vector<ttl::string_base<char>, ttl::vector_allocators::heap_allocator<ttl::string_base<char>>, 1>&, ttl::vector<ttl::string_base<char>, ttl::vector_allocators::heap_allocator<ttl::string_base<char>>, 1>&) const;
		virtual void _StrippedVFunc4() = 0;
		virtual void _StrippedVFunc5() = 0;
		VIRTUAL_CALL(11, int64_t, _RunUnitTests2, ());
		VIRTUAL_CALL(12, bool, _updateRttiParams1, ());
		virtual void _StrippedVFunc6() = 0;
		virtual void _StrippedVFunc7() = 0;
		virtual void _StrippedVFunc8() = 0;
		VIRTUAL_CALL(16, int64_t, _RunUnitTests3, ());
		GAME_IMPORT virtual bool Copy(CRTTIObject*, CRTTIObject const*) const;
		GAME_IMPORT virtual bool Exchange(CRTTIObject*, CRTTIObject*) const;
		VIRTUAL_CALL(19, bool, _updateRttiParams2, ());
		GAME_IMPORT virtual ttl::string_base<char> const ClampString(char const*) const;
		VIRTUAL_CALL(21, int64_t, _RunUnitTests4, ());
		GAME_IMPORT virtual bool AddVirtualFieldDestination(CRTTIField const*, uint32_t, ttl::string_base<char>*);
		VIRTUAL_CALL(23, bool, _updateRttiParams3, ());
		VIRTUAL_CALL(24, int64_t, _RunUnitTests5, ());
		VIRTUAL_CALL(25, void, SetPlatform, ());
		GAME_IMPORT virtual bool OverwriteVirtualFieldFlags(CRTTIField const*);
		VIRTUAL_CALL(27, int64_t, _RunUnitTests6, ());
		VIRTUAL_CALL(28, void, _SetPlatform1, ());
		VIRTUAL_CALL(29, int64_t, _RunUnitTests7, ());
		VIRTUAL_CALL(30, void, _SetPlatform2, ());
		GAME_IMPORT virtual void WriteToDom(dom::IWriter&, CRTTIObject const*) const;
		GAME_IMPORT virtual void ReadFromDom(dom::IReader::Array const&, CRTTIObject*) const;
	protected:
		GAME_IMPORT virtual bool ParseInitToken(char, char const*);
		GAME_IMPORT virtual void ParseFlagsTokenData(char const*, uint32_t64_t);
		GAME_IMPORT virtual void ParseEditorFlagsTokenData(ERTTIEditFlags&, char const*, uint32_t64_t);
	public:
		GAME_IMPORT virtual ttl::string_base<char> ClassWriterCompare(CRTTI const*, CRTTI const*, CRTTIField const&) const;

		GAME_IMPORT CRTTIField(ClassReaderResolve const&);
		GAME_IMPORT ERTTIType GetType() const;
		GAME_IMPORT bool IsMessagePipeIn() const;
		GAME_IMPORT bool HasIndividualSize() const;
		GAME_IMPORT bool IsUuidRefFlagSet() const;
		GAME_IMPORT bool IsEditable() const;
		GAME_IMPORT CRTTIField();
		GAME_IMPORT bool Initialize(ttl::string_const<char>, ttl::string_const<char>, unsigned char, void (* )( ttl::vector<ttl::string_base<char>, ttl::vector_allocators::heap_allocator<ttl::string_base<char>>, 1>&, ttl::vector<ttl::string_base<char>, ttl::vector_allocators::heap_allocator<ttl::string_base<char>>, 1>& ));
		GAME_IMPORT bool IsPStorageField() const;
		GAME_IMPORT bool IsPropertyIn() const;
		GAME_IMPORT bool HasStaticSize() const;
		GAME_IMPORT bool IsGamescript() const;
		GAME_IMPORT bool IsVirtual() const;
		GAME_IMPORT char const* GetName() const;
		GAME_IMPORT void GetDefaultValue(CRTTI const*, CRTTIField::Variant&) const;
		GAME_IMPORT bool IsFieldInternal() const;
	protected:
		GAME_IMPORT void SetDefaultValueInternal(CRTTI const*, CRTTIField::Variant*);
	public:
		GAME_IMPORT void SetExposed(bool) const;
		GAME_IMPORT bool IsProperty() const;
		GAME_IMPORT bool HasDefaultValue() const;
		GAME_IMPORT bool IsMessagePipe() const;
		GAME_IMPORT bool IsExposed() const;
		GAME_IMPORT bool IsPresetFlagSet() const;
		GAME_IMPORT ttl::pstring GetSubtype() const;
		GAME_IMPORT void SetExpanded(bool) const;
	protected:
		GAME_IMPORT void SetVirtualFlag();
		GAME_IMPORT static bool EatWhiteChars(char* &);
		GAME_IMPORT void SetPropertyFlag();
	public:
		GAME_IMPORT bool IsPipeInternal() const;
		GAME_IMPORT void SetPipeInternal(bool) const;
		GAME_IMPORT bool IsReplicated() const;
		GAME_IMPORT void RestoreDefaultValue(CRTTI const*, CRTTIObject*);
		GAME_IMPORT bool IsQuestField() const;
		GAME_IMPORT void SetGamescript(bool) const;
		GAME_IMPORT char const* GetPreviousName() const;
		GAME_IMPORT bool IsSaveGameField() const;
		GAME_IMPORT bool IsSelfUuidFlagSet() const;
	protected:
		GAME_IMPORT char const* ExtractClassName(CRTTI const*) const;
	public:
		GAME_IMPORT void SetEditable(bool) const;
		GAME_IMPORT bool IsPropertyOut() const;
		GAME_IMPORT bool HasDynamicSize() const;
		GAME_IMPORT bool IsMessagePipeOut() const;
	protected:
		GAME_IMPORT void SetPrecision(int);
	public:
		GAME_IMPORT CRTTIField(CRTTIField const&);
		GAME_IMPORT void SetPresetFlag(bool) const;
		GAME_IMPORT bool CmpName(char const*) const;
		GAME_IMPORT bool IsExpanded() const;
		GAME_IMPORT bool HasDefaultValue(CRTTI const*) const;
		GAME_IMPORT void SetSerialize(bool) const;
		GAME_IMPORT bool IsSerialize() const;
#pragma endregion
};