#pragma once
#include <EGSDK\ClassHelpers.h>

namespace EGSDK::Engine {
	class EGameSDK_API CVideoSettings {
#pragma region GENERATED by ExportClassToCPPH.py
	public:
		VIRTUAL_CALL(0, char*, sub_7DCAB0, (char a1), a1);

		GAME_IMPORT void SetIsSavingEnabled(bool);
		GAME_IMPORT bool IsSavingEnabled() const;
#pragma endregion
	public:
		union {
			DynamicField(CVideoSettings, float, extraFOV);
		};

		static CVideoSettings* Get();
	};
}