#pragma once
#include <optional>
#include <EGSDK\Imports.h>
#include <EGSDK\Engine\rtti.h>
#include <EGSDK\Engine\IClassWriter.h>
#include <EGSDK\Engine\ttl\vector_allocators\heap_allocator.h>
#include <EGSDK\Engine\ttl\vector.h>
#include <EGSDK\Engine\ttl\set.h>
#include <EGSDK\Engine\ttl\less.h>
#include <EGSDK\Engine\ttl\list.h>
#include <EGSDK\Engine\ttl\allocator.h>
#include <EGSDK\Engine\ttl\function_ref.h>
#include <EGSDK\Engine\Uid.h>
#include <EGSDK\Engine\IPtrResolver.h>
#include <EGSDK\Engine\ClassReaderResolve.h>
#include <EGSDK\vec3.h>
#include <EGSDK\vec4.h>

class MED {
public:
	class SModelOutfitGroup;
};

class cbs {
public:
	class prop {
	public:
		class IPropertySet;
	};

	class msg {
	public:
		class IMessagePipeSet;
	};
};

class CRTTIObject;

class IGSObject {
#pragma region GENERATED by ExportClassToCPPH.py
	public:
		GAME_IMPORT static bool __INTERNAL_crtti_fields_initialized_field;
		GAME_IMPORT static rtti::Type& m_RTTI;

		GAME_IMPORT virtual void ClassWriterSave(IClassWriter*, bool) const;
		VIRTUAL_CALL(1, IGSObject*, sub_11FF80, (char a1), a1);
		VIRTUAL_CALL(2, static CRTTIGameScript<IGSObject>*, GetSTTI, ());
		GAME_IMPORT virtual CRTTI const* GetEngineRTTI() const;
	protected:
		VIRTUAL_CALL(4, gui::CPackage*, ToCPackage, ());
	public:
		VIRTUAL_CALL(5, gui::CPackage*, _ToCPackage1, ());
		VIRTUAL_CALL(6, MED::SModelOutfitGroup const*, unassigned, ());
		VIRTUAL_CALL(7, MED::SModelOutfitGroup const*, _unassigned1, ());
		VIRTUAL_CALL(8, int64_t, RunUnitTests, ());
		VIRTUAL_CALL(9, int64_t, _RunUnitTests1, ());
		GAME_IMPORT virtual void GetPrivateObjects(ttl::list<IGSObject*, ttl::allocator>*, bool, bool);
		GAME_IMPORT virtual void DestroyPrivateObjects();
		VIRTUAL_CALL(12, int64_t, _RunUnitTests2, ());
		GAME_IMPORT virtual void GetAllObjects(ttl::vector<IGSObject*, ttl::vector_allocators::heap_allocator<IGSObject*>, 1>&, bool);
		GAME_IMPORT virtual void GetAllObjects(ttl::set<CRTTIObject*, ttl::less<CRTTIObject*>, ttl::allocator>&, ttl::set<CRTTIObject*, ttl::less<CRTTIObject*>, ttl::allocator>&, bool, std::optional<ttl::function_ref<bool ( CRTTIObject* )>>);
		VIRTUAL_CALL(15, bool, updateRttiParams, ());
		VIRTUAL_CALL(16, void, SetPlatform, ());
		GAME_IMPORT virtual char const* GetString(char const*) const;
		VIRTUAL_CALL(18, void, _SetPlatform1, ());
		VIRTUAL_CALL(19, static bool, ValidateVec4, (IGSObject const*, vec4 const&), const*, const&);
		VIRTUAL_CALL(20, void, _SetPlatform2, ());
		VIRTUAL_CALL(21, MED::SModelOutfitGroup const*, _unassigned2, ());
		VIRTUAL_CALL(22, void, _SetPlatform3, ());
		GAME_IMPORT virtual Uid const& GetUid() const;
		VIRTUAL_CALL(24, bool, _updateRttiParams1, ());
		VIRTUAL_CALL(25, bool, _updateRttiParams2, ());
		VIRTUAL_CALL(26, bool, _updateRttiParams3, ());
		VIRTUAL_CALL(27, bool, _updateRttiParams4, ());
		VIRTUAL_CALL(28, bool, _updateRttiParams5, ());
		VIRTUAL_CALL(29, bool, _updateRttiParams6, ());
		VIRTUAL_CALL(30, bool, _updateRttiParams7, ());
		VIRTUAL_CALL(31, bool, _updateRttiParams8, ());
		VIRTUAL_CALL(32, bool, _updateRttiParams9, ());
		GAME_IMPORT virtual void CallVoidMethod(char const*, ...);
		GAME_IMPORT virtual cbs::msg::IMessagePipeSet const& GetMessagePipeSet() const;
		VIRTUAL_CALL(35, int64_t, _RunUnitTests3, ());
		VIRTUAL_CALL(36, MED::SModelOutfitGroup const*, _unassigned3, ());
		VIRTUAL_CALL(37, MED::SModelOutfitGroup const*, _unassigned4, ());
		VIRTUAL_CALL(38, MED::SModelOutfitGroup const*, _unassigned5, ());
		VIRTUAL_CALL(39, MED::SModelOutfitGroup const*, _unassigned6, ());
		GAME_IMPORT virtual cbs::prop::IPropertySet const& GetPropertySet() const;
		VIRTUAL_CALL(41, void, _SetPlatform4, ());
		VIRTUAL_CALL(42, int64_t, _RunUnitTests4, ());
		GAME_IMPORT virtual bool LoadField(CRTTIField const*, unsigned char, fs::ifile&, IPtrResolver&, bool);
		GAME_IMPORT virtual void LoadFields(dom::IReader::Object const&, IPtrResolver&, bool, bool (* )(char const*, CRTTIObject* ));
		GAME_IMPORT virtual void LoadFields(ITextDeserializer&, IPtrResolver&, bool);
		GAME_IMPORT virtual void LoadFields(fs::ifile&, IPtrResolver&, bool);
		GAME_IMPORT virtual void SaveFields(dom::IWriter&, ERTTIFlags, bool) const;
		GAME_IMPORT virtual int ToBufferReplicated(char*, int);
		GAME_IMPORT virtual int FromBufferReplicated(char*, int);
		GAME_IMPORT virtual int GetBufferReplicatedDataSize();
		VIRTUAL_CALL(51, void, _SetPlatform5, ());
		VIRTUAL_CALL(52, static bool, _ValidateVec41, (IGSObject const* a1, vec4 const& a2), a1, a2);
		GAME_IMPORT virtual bool CopyFields(CRTTIObject const*, bool);
		GAME_IMPORT virtual bool CopyPointerFields(CRTTIObject const*);
		GAME_IMPORT virtual bool ExchangePointerFields(CRTTIObject*);
		GAME_IMPORT virtual IGSObject* FindObjectByID(int) const;
		GAME_IMPORT virtual IGSObject* FindObjectByNetPointer(SRttiNetPointer const&) const;
		GAME_IMPORT virtual cbs::CEntity* FindEntityByNetPointer(SRttiNetPointer const&) const;
		GAME_IMPORT virtual SRttiNetPointer GetNetPointer() const;
		VIRTUAL_CALL(60, int64_t, _RunUnitTests5, ());
		GAME_IMPORT virtual ttl::string_base<char> GetDebugDescription() const;
		GAME_IMPORT virtual void CalcMemoryUsage(SObjectMemoryUsage&) const;
		VIRTUAL_CALL(63, void, _SetPlatform6, ());
		VIRTUAL_CALL(64, bool, _updateRttiParams10, ());
		VIRTUAL_CALL(65, bool, _updateRttiParams11, ());
		VIRTUAL_CALL(66, static bool, _ValidateVec42, (IGSObject const* a1, vec4 const& a2), a1, a2);
		VIRTUAL_CALL(67, int64_t, _RunUnitTests6, ());
		GAME_IMPORT virtual ttl::string_base<char> ValueToString(CRTTIObject* const&) const;
		GAME_IMPORT virtual bool IsFieldChanged(CRTTIField const*) const;
		GAME_IMPORT virtual void SetFieldChangedFlag(CRTTIField const*, bool);
		VIRTUAL_CALL(71, bool, _updateRttiParams12, ());
		GAME_IMPORT virtual bool OnFieldChanged2(CRTTIField const*, bool);
		VIRTUAL_CALL(73, void, _SetPlatform7, ());
		GAME_IMPORT virtual char const* GetPresetsData() const;
		VIRTUAL_CALL(75, void, _SetPlatform8, ());
		VIRTUAL_CALL(76, bool, _updateRttiParams13, ());
	private:
		GAME_IMPORT virtual bool OnFieldChanged(CRTTIField const*, bool);
	public:
		VIRTUAL_CALL(78, bool, _updateRttiParams14, ());
		VIRTUAL_CALL(79, bool, _updateRttiParams15, ());
		VIRTUAL_CALL(80, int64_t, _RunUnitTests7, ());
		VIRTUAL_CALL(81, int64_t, _RunUnitTests8, ());
		VIRTUAL_CALL(82, void, _SetPlatform9, ());
		GAME_IMPORT virtual void Query(IBaseValidator&, ttl::vector<CRTTIObject*, ttl::vector_allocators::heap_allocator<CRTTIObject*>, 1>&) const;
	protected:
		GAME_IMPORT virtual void SetEngineObject(CGSObject*);
	public:
		VIRTUAL_CALL(85, MED::SModelOutfitGroup const*, _unassigned7, ());
		VIRTUAL_CALL(86, MED::SModelOutfitGroup const*, _unassigned8, ());
		VIRTUAL_CALL(87, int64_t, _RunUnitTests9, ());
		VIRTUAL_CALL(88, int64_t, _RunUnitTests10, ());
		VIRTUAL_CALL(89, int64_t, _RunUnitTests11, ());
		VIRTUAL_CALL(90, int64_t, _RunUnitTests12, ());
		VIRTUAL_CALL(91, int64_t, _RunUnitTests13, ());
		VIRTUAL_CALL(92, int64_t, _RunUnitTests14, ());
		VIRTUAL_CALL(93, int64_t, _RunUnitTests15, ());
		VIRTUAL_CALL(94, int64_t, _RunUnitTests16, ());
		VIRTUAL_CALL(95, void, _SetPlatform10, ());
		GAME_IMPORT virtual ttl::string_base<char> toString() const;
		VIRTUAL_CALL(97, void, _SetPlatform11, ());
		VIRTUAL_CALL(98, void, _SetPlatform12, ());
		VIRTUAL_CALL(99, bool, _updateRttiParams16, ());
		VIRTUAL_CALL(100, void, _SetPlatform13, ());
		VIRTUAL_CALL(101, void, _SetPlatform14, ());
		VIRTUAL_CALL(102, void, _SetPlatform15, ());
		VIRTUAL_CALL(103, void, _SetPlatform16, ());
		VIRTUAL_CALL(104, void, _SetPlatform17, ());
		VIRTUAL_CALL(105, void, _SetPlatform18, ());
		VIRTUAL_CALL(106, void, _SetPlatform19, ());
	private:
		VIRTUAL_CALL(107, void, UnregisterInTimeHandlerManager, ());
	public:
		VIRTUAL_CALL(108, void, _UnregisterInTimeHandlerManager1, ());
		VIRTUAL_CALL(109, void, _SetPlatform20, ());
		VIRTUAL_CALL(110, void, _SetPlatform21, ());
		VIRTUAL_CALL(111, void, _SetPlatform22, ());
		VIRTUAL_CALL(112, void, _SetPlatform23, ());
		VIRTUAL_CALL(113, void, _SetPlatform24, ());
		VIRTUAL_CALL(114, void, _SetPlatform25, ());
		VIRTUAL_CALL(115, void, _SetPlatform26, ());
		VIRTUAL_CALL(116, void, _SetPlatform27, ());
		VIRTUAL_CALL(117, void, _SetPlatform28, ());
		VIRTUAL_CALL(118, void, _SetPlatform29, ());
		VIRTUAL_CALL(119, void, _SetPlatform30, ());
		VIRTUAL_CALL(120, void, _SetPlatform31, ());
		GAME_IMPORT virtual void OnActivateOnModule();
		VIRTUAL_CALL(122, void, _SetPlatform32, ());
		VIRTUAL_CALL(123, void, _SetPlatform33, ());
		VIRTUAL_CALL(124, void, _SetPlatform34, ());
		VIRTUAL_CALL(125, void, _SetPlatform35, ());
		VIRTUAL_CALL(126, void, _SetPlatform36, ());
		VIRTUAL_CALL(127, void, _SetPlatform37, ());
		VIRTUAL_CALL(128, void, _SetPlatform38, ());
		VIRTUAL_CALL(129, void, _SetPlatform39, ());
		VIRTUAL_CALL(130, void, _SetPlatform40, ());
		VIRTUAL_CALL(131, void, _SetPlatform41, ());
		VIRTUAL_CALL(132, void, _SetPlatform42, ());
		VIRTUAL_CALL(133, void, _SetPlatform43, ());
		VIRTUAL_CALL(134, void, _SetPlatform44, ());
		VIRTUAL_CALL(135, void, _SetPlatform45, ());
		VIRTUAL_CALL(136, void, _SetPlatform46, ());
		VIRTUAL_CALL(137, void, _SetPlatform47, ());
		VIRTUAL_CALL(138, void, _SetPlatform48, ());
		VIRTUAL_CALL(139, void, _SetPlatform49, ());
		VIRTUAL_CALL(140, bool, _updateRttiParams17, ());
		GAME_IMPORT virtual void SetHiddenByLogicEditor(bool);
		VIRTUAL_CALL(142, void, _SetPlatform50, ());
		VIRTUAL_CALL(143, static bool, _ValidateVec43, (IGSObject const* a1, vec4 const& a2), a1, a2);
		VIRTUAL_CALL(144, static bool, _ValidateVec44, (IGSObject const* a1, vec4 const& a2), a1, a2);
		VIRTUAL_CALL(145, static bool, _ValidateVec45, (IGSObject const* a1, vec4 const& a2), a1, a2);
		VIRTUAL_CALL(146, static bool, _ValidateVec46, (IGSObject const* a1, vec4 const& a2), a1, a2);
		VIRTUAL_CALL(147, static bool, _ValidateVec47, (IGSObject const* a1, vec4 const& a2), a1, a2);
		VIRTUAL_CALL(148, static bool, _ValidateVec48, (IGSObject const* a1, vec4 const& a2), a1, a2);
		VIRTUAL_CALL(149, static bool, _ValidateVec49, (IGSObject const* a1, vec4 const& a2), a1, a2);
		VIRTUAL_CALL(150, static bool, _ValidateVec410, (IGSObject const* a1, vec4 const& a2), a1, a2);
		VIRTUAL_CALL(151, static bool, _ValidateVec411, (IGSObject const* a1, vec4 const& a2), a1, a2);
		VIRTUAL_CALL(152, static bool, _ValidateVec412, (IGSObject const* a1, vec4 const& a2), a1, a2);
		VIRTUAL_CALL(153, static bool, _ValidateVec413, (IGSObject const* a1, vec4 const& a2), a1, a2);
		VIRTUAL_CALL(154, static bool, _ValidateVec414, (IGSObject const* a1, vec4 const& a2), a1, a2);
		VIRTUAL_CALL(155, static bool, _ValidateVec415, (IGSObject const* a1, vec4 const& a2), a1, a2);
		VIRTUAL_CALL(156, static bool, _ValidateVec416, (IGSObject const* a1, vec4 const& a2), a1, a2);
		VIRTUAL_CALL(157, static bool, _ValidateVec417, (IGSObject const* a1, vec4 const& a2), a1, a2);
		VIRTUAL_CALL(158, static bool, _ValidateVec418, (IGSObject const* a1, vec4 const& a2), a1, a2);
		VIRTUAL_CALL(159, static bool, _ValidateVec419, (IGSObject const* a1, vec4 const& a2), a1, a2);
		VIRTUAL_CALL(160, static bool, _ValidateVec420, (IGSObject const* a1, vec4 const& a2), a1, a2);
		VIRTUAL_CALL(161, static bool, _ValidateVec421, (IGSObject const* a1, vec4 const& a2), a1, a2);
		VIRTUAL_CALL(162, static bool, _ValidateVec422, (IGSObject const* a1, vec4 const& a2), a1, a2);
		VIRTUAL_CALL(163, static bool, _ValidateVec423, (IGSObject const* a1, vec4 const& a2), a1, a2);
		VIRTUAL_CALL(164, static bool, _ValidateVec424, (IGSObject const* a1, vec4 const& a2), a1, a2);
		GAME_IMPORT virtual void SetSerializable(bool);
		VIRTUAL_CALL(166, void, _SetPlatform51, ());
		VIRTUAL_CALL(167, bool, _updateRttiParams18, ());
		VIRTUAL_CALL(168, bool, _updateRttiParams19, ());
		GAME_IMPORT virtual void DeactivateOnModule();
		VIRTUAL_CALL(170, void, _SetPlatform52, ());
		VIRTUAL_CALL(171, ttl::list<SCommandParam, ttl::allocator>::const_reverse_iterator, rend, ());
		VIRTUAL_CALL(172, void, _SetPlatform53, ());
		GAME_IMPORT virtual bool ISharedObject_IsValid() const;
		GAME_IMPORT virtual float GetTime() const;
		GAME_IMPORT virtual float GetLastTime() const;
		GAME_IMPORT virtual float GetTimeDelta() const;
		GAME_IMPORT virtual int64_t GetTimeDeltaMiliseconds() const;

		GAME_IMPORT void DisableOnFrameEditorHandler();
		GAME_IMPORT void EnableOnPostUpdateEditorHandler();
		GAME_IMPORT void CallMethodEvery(CRTTIVoidMethod const*, float, float) const;
		GAME_IMPORT ttl::string_const<char> GetPresetsDataStr() const;
		GAME_IMPORT float ReplGetRelevance(unsigned short) const;
		GAME_IMPORT IGSObject* CreateObjectWithID(rtti::Type const&, int, bool, ttl::string_base<char> const*);
		GAME_IMPORT IGpuFx_Manager* GetGpuFxManager();
		GAME_IMPORT virtual void OnKeyboardClosed(ttl::string_base<wchar_t>);
		GAME_IMPORT uint32_t EditorGetAttributeMarkedToSaveCount() const;
		GAME_IMPORT bool ReplIsOwner() const;
		GAME_IMPORT bool ReplIsReplicated() const;
		GAME_IMPORT void CallMethodIn(CRTTIVoidMethod const*, float) const;
		GAME_IMPORT bool EditorIsSelected() const;
		GAME_IMPORT bool ReplIsReplicable() const;
		GAME_IMPORT ttl::string_base<char> ReplGetRequestingString() const;
		GAME_IMPORT void EnableOnFrameHandler(EFrameHandlerPriority::TYPE, bool);
		GAME_IMPORT bool IsActiveOnModule() const;
		GAME_IMPORT void DisableOnPostAnimUpdateHandler();
	private:
		GAME_IMPORT static bool __INTERNAL_crtti_fields_initialized_function();
	public:
		GAME_IMPORT void SetGSOFlags(uint32_t64_t);
		GAME_IMPORT void SetComment(ttl::string_base<wchar_t> const&);
		GAME_IMPORT void EnableOnPostUpdateHandler(EFrameHandlerPriority::TYPE, bool);
		GAME_IMPORT ILevel* GetLevel() const;
		GAME_IMPORT void MakePrivate(IGSObject*);
		GAME_IMPORT void SetLevel(CLevel*, bool);
		GAME_IMPORT void SetAndProcessPresets(ttl::string_base<char> const&);
		GAME_IMPORT EMem::TYPE GetMemCategory();
	private:
		GAME_IMPORT void ActivateOnModuleInternal();
	public:
		GAME_IMPORT char const* GetNameCStr() const;
		GAME_IMPORT IGSObject* CreateObjectWithID(CRTTI const&, int, bool, ttl::string_base<char> const*);
		GAME_IMPORT void DisableOnPostAnimatorUpdateHandler();
		GAME_IMPORT int GetLocalClientId() const;
		GAME_IMPORT float ReplGetRelevance() const;
		GAME_IMPORT void ProcessPresets(PresetId);
		GAME_IMPORT void SetName(ttl::string_base<char> const&);
		GAME_IMPORT ttl::string_base<char> const GetNameAndClass() const;
		GAME_IMPORT IGSObject* CreateObject(EEntityRootType::TYPE, CRTTI const&, std::optional<Replication::CreateObjectOptions>, bool, ttl::string_base<char> const*);
		GAME_IMPORT void AcquireObjectModule(IGSObject*);
		GAME_IMPORT void RequestOwnership();
		GAME_IMPORT bool IsCreating() const;
		GAME_IMPORT ttl::string_base<char> GetName() const;
		GAME_IMPORT void DisableCallMethod(CRTTIVoidMethod const*) const;
		GAME_IMPORT void MultiRaytest(unsigned char, vec3 const&, ttl::vector<vec3, ttl::vector_allocators::heap_allocator<vec3>, 0> const&, ttl::vector<bool, ttl::vector_allocators::heap_allocator<bool>, 8>&, unsigned short, bool, IControlObject*, cbs::CEntity*, uint32_t, unsigned short, int64_t);
		GAME_IMPORT wchar_t const* GetComment() const;
	private:
		GAME_IMPORT void DeactivateOnModuleInternal();
	public:
		GAME_IMPORT unsigned char ReplGetObjectIdx() const;
		GAME_IMPORT IGSObject(IGSObject const&);
		GAME_IMPORT void EnableOnPostAnimatorUpdateHandler();
		GAME_IMPORT void ReplSetLocalReplicationInterval(float, float);
		GAME_IMPORT void EditorRemoveAtCompilation(bool);
		GAME_IMPORT bool IsLevelShutdown();
		GAME_IMPORT void EnableOnPostAnimUpdateHandler();
		GAME_IMPORT uint64_t GetGSOFlags() const;
		GAME_IMPORT CRTTIField const* EditorGetAttributeMarkedToSave(uint32_t) const;
		GAME_IMPORT void EditorMarkAttributeToSave(ttl::string_base<char> const&);
		GAME_IMPORT void FinalizeReplicationObject();
	protected:
		GAME_IMPORT IGSObject();
	public:
		GAME_IMPORT void InitializeReplicationObject(Replication::CreateObjectOptions);
		GAME_IMPORT void EnableOnPreAnimUpdateHandler();
		GAME_IMPORT void ReplSetRelevance(float);
		GAME_IMPORT IGSObject* GetPrivateOwner();
		GAME_IMPORT IGSObject& operator=(IGSObject const&);
		GAME_IMPORT void PreDestroy();
	private:
		GAME_IMPORT static CRTTI* __INTERNAL_crtti_factory();
	public:
		GAME_IMPORT unsigned char Raytrace(unsigned char, SCollision*, vec3 const&, vec3&, unsigned short, bool, IControlObject*, uint32_t, unsigned short, int64_t, ttl::span<cbs::CEntity const*, 4294967295>);
		GAME_IMPORT IGSObject(ClassReaderResolve const&);
		GAME_IMPORT bool ReplIsAuthoritative() const;
		GAME_IMPORT void DisableOnPostUpdateEditorHandler();
		GAME_IMPORT Net::Repl::CObjectId ReplGetId() const;
		GAME_IMPORT uint32_t PlayAudioEvent(ttl::string_base<char> const&, Audio::SAudioEventExtraData const*, vec3 const&);
		GAME_IMPORT bool EditorIsRemoveAtCompilationSet();
		GAME_IMPORT bool ReplIsBlockChangeOwnership() const;
		GAME_IMPORT PresetId GetPresetsId() const;
		GAME_IMPORT void ProcessPresets(ttl::string_base<char> const&);
		GAME_IMPORT Replication::IObject const& ReplicationObject() const;
		GAME_IMPORT ttl::string_base<char> ReplGetAuthoritativeString() const;
		GAME_IMPORT void SetIGSOFlags(uint64_t);
	private:
		GAME_IMPORT static rtti::Type& __INTERNAL_type_factory();
	public:
		GAME_IMPORT void DisableOnPreAnimUpdateHandler();
		GAME_IMPORT unsigned short ReplGetOwnerId() const;
		GAME_IMPORT void ActivateOnModule();
		GAME_IMPORT static rtti::Type& typeinfo();
		GAME_IMPORT IGSObject* CreateObjectWithGuid(rtti::Type const&, uint64_t, bool, ttl::string_base<char> const*);
		GAME_IMPORT void ReplBlockChangeOwnership(bool);
		GAME_IMPORT void ReplSendNow();
		GAME_IMPORT void ReplSetRelevance(unsigned short, float);
		GAME_IMPORT bool Raytest(unsigned char, vec3 const&, vec3 const&, unsigned short, bool, IControlObject*, uint32_t, unsigned short, int64_t, ttl::span<cbs::CEntity const*, 4294967295>);
		GAME_IMPORT void DeleteThis();
		GAME_IMPORT bool EditorIsNeverStatic() const;
		GAME_IMPORT void DisableOnPostUpdateHandler();
		GAME_IMPORT void ClearGSOFlags(uint64_t);
		GAME_IMPORT void DisableOnFrameHandler();
		GAME_IMPORT unsigned short ReplGetAuthoritativeId() const;
		GAME_IMPORT void SetReplicationRelevance(float);
		GAME_IMPORT void InitObject(IGSObject*);
		GAME_IMPORT IGSObject* CreateObject(EEntityRootType::TYPE, CRTTI const&, bool, ttl::string_base<char> const*, bool);
		GAME_IMPORT void ClearIGSOFlags(uint64_t);
		GAME_IMPORT static void RegisterSTTI(CRTTI*);
		GAME_IMPORT void EnableOnFrameEditorHandler();
		GAME_IMPORT bool ReplIsOwnerNoLocal() const;
		GAME_IMPORT IGSObject* GetNext() const;
		GAME_IMPORT IGSObject* CreateObjectWithGuid(CRTTI const&, uint64_t, bool, ttl::string_base<char> const*);
		GAME_IMPORT bool IsDestroying() const;
		GAME_IMPORT bool IsCreated() const;
		GAME_IMPORT int GetNetOwnerID() const;
		GAME_IMPORT bool IsPrivate() const;
		GAME_IMPORT bool GetNetIsUniqueOwner() const;
		GAME_IMPORT int GetID() const;
		GAME_IMPORT void SetAndProcessPresets(PresetId);
		GAME_IMPORT bool IsDestroyed() const;
		GAME_IMPORT void SetIsReplicationEnabled(bool);
#pragma endregion
};