#pragma once
#include <functional>
#include <EGSDK\Imports.h>
#include <EGSDK\Engine\ttl\string_base.h>
#include <EGSDK\Engine\ttl\string_const.h>
#include <EGSDK\Engine\ttl\map.h>
#include <EGSDK\Engine\ttl\less.h>
#include <EGSDK\Engine\ttl\list.h>
#include <EGSDK\Engine\ttl\set.h>
#include <EGSDK\Engine\ttl\vector.h>
#include <EGSDK\Engine\ttl\allocator.h>
#include <EGSDK\Engine\ttl\vector_allocators\heap_allocator.h>
#include <EGSDK\Engine\parser.h>
#include <EGSDK\Engine\IMaterial.h>
#include <EGSDK\Engine\MaterialEditorCommon.h>

class cbs {
public:
	class CComponent;
};

class MED {
public:
	enum HeadType;
	enum SkeletonType;
	enum EPropertyConfig;
	enum ModelUsage;
	enum EnumItemType;
	enum EnumGroupType;
	enum ModelSlotPresetType;
	enum LodVisibilityPreset;
	enum EditorSceneSetup;

	struct SEditorSceneSetupData {
#pragma region GENERATED by ExportClassToCPPH.py
	public:
		GAME_IMPORT SEditorSceneSetupData();
#pragma endregion
	};

	struct SModelOutfitGroup {
#pragma region GENERATED by ExportClassToCPPH.py
	public:
		GAME_IMPORT static char const* const UNASSIGNED_GROUP_NAME;

		GAME_IMPORT SModelOutfitGroup();
		GAME_IMPORT void write(parser::writer*) const;
		GAME_IMPORT SModelOutfitGroup(MED::SModelOutfitGroup&&);
		GAME_IMPORT bool isUnassignedName() const;
		GAME_IMPORT bool read(parser::func_iterator const&);
		GAME_IMPORT MED::SModelOutfitGroup& operator=(MED::SModelOutfitGroup&&);
		GAME_IMPORT ttl::string_base<char> labelText() const;
		GAME_IMPORT bool operator==(MED::SModelOutfitGroup const&) const;
		GAME_IMPORT SModelOutfitGroup(MED::SModelOutfitGroup const&);
		GAME_IMPORT MED::SModelOutfitGroup& operator=(MED::SModelOutfitGroup const&);
		GAME_IMPORT ttl::string_base<char> toDebugString() const;
#pragma endregion
	};

	class CMaterialTemplate {
	public:
		struct FieldDefinition {
#pragma region GENERATED by ExportClassToCPPH.py
		private:
			GAME_IMPORT bool isSection(ttl::string_base<char> const&);
		public:
			GAME_IMPORT bool isTypeSupported();
			GAME_IMPORT FieldDefinition(MED::CMaterialTemplate::FieldDefinition const&);
			GAME_IMPORT ttl::string_const<char> parameterCategory() const;
		private:
			GAME_IMPORT void initialize(MaterialEditorCommon::TemplateDesc::Parameter&);
		public:
			GAME_IMPORT ttl::string_base<char> getDescription() const;
			GAME_IMPORT ttl::string_const<char> typeString() const;
			GAME_IMPORT ttl::string_base<char> toDebugString() const;
			GAME_IMPORT FieldDefinition(MED::CMaterialTemplate::FieldDefinition&&);
			GAME_IMPORT MED::CMaterialTemplate::FieldDefinition& operator=(MED::CMaterialTemplate::FieldDefinition&&);
		private:
			GAME_IMPORT ttl::string_base<char> section(ttl::string_base<char> const&);
		public:
			GAME_IMPORT ttl::map<int, ttl::string_base<char>, ttl::less<int>, ttl::allocator> const& mapEnum() const;
			GAME_IMPORT bool isTypeString() const;
			GAME_IMPORT bool isFieldVisible();
			GAME_IMPORT ttl::string_const<char> parameterLabel() const;
			GAME_IMPORT ttl::string_base<char> parameterLowercaseLabel() const;
			GAME_IMPORT FieldDefinition();
		private:
			GAME_IMPORT static ttl::string_base<char> normalizeCategoryName(ttl::string_base<char>);
		public:
			GAME_IMPORT parser::EVarType const& type() const;
		private:
			GAME_IMPORT ttl::map<int, ttl::string_base<char>, ttl::less<int>, ttl::allocator> decodeEnum(ttl::string_base<char> const&);
		public:
			GAME_IMPORT ttl::string_base<char> parameterPath() const;
			GAME_IMPORT MED::CMaterialTemplate::FieldDefinition& operator=(MED::CMaterialTemplate::FieldDefinition const&);
			GAME_IMPORT bool isPresetValueEmpty() const;
#pragma endregion
		};

		struct Parameter {
#pragma region GENERATED by ExportClassToCPPH.py
		public:
			GAME_IMPORT ttl::string_base<char> toNameString();
			GAME_IMPORT MED::CMaterialTemplate::Parameter& operator=(MED::CMaterialTemplate::Parameter const&);
			GAME_IMPORT Parameter(MED::CMaterialTemplate::Parameter&&);
			GAME_IMPORT void initialize(MED::CMaterialTemplate::FieldDefinition&);
			GAME_IMPORT Parameter();
			GAME_IMPORT MED::CMaterialTemplate::Parameter& operator=(MED::CMaterialTemplate::Parameter&&);
			GAME_IMPORT Parameter(MED::CMaterialTemplate::Parameter const&);
			GAME_IMPORT ttl::string_base<char> toString();
#pragma endregion
		};

#pragma region GENERATED by ExportClassToCPPH.py
	public:
		VIRTUAL_CALL(0, MED::CMaterialTemplate*, sub_11C2D0, (char a1), a1);

		GAME_IMPORT void queryData(IMaterial*);
		GAME_IMPORT static std::initializer_list<ttl::string_base<char>>& fixedMaterialParametersLabelsForSearch();
		GAME_IMPORT CMaterialTemplate(MED::CMaterialTemplate const&);
		GAME_IMPORT MaterialEditorCommon::TemplateDesc::Parameter const* parameter(parser::EVarType, ttl::string_base<char> const&) const;
		GAME_IMPORT void getMaterialParametersByLabel(ttl::list<MED::CMaterialTemplate::Parameter, ttl::allocator>&, ttl::string_base<char> const&, ttl::string_base<char> const&);
		GAME_IMPORT ttl::list<MED::CMaterialTemplate::FieldDefinition, ttl::allocator> const& fields();
		GAME_IMPORT static std::initializer_list<ttl::string_base<char>>& fixedMaterialParametersLabelsForEdit();
		GAME_IMPORT MED::CMaterialTemplate::FieldDefinition const* fieldByName(ttl::string_base<char> const&) const;
		GAME_IMPORT CMaterialTemplate();
	private:
		GAME_IMPORT void updateFieldsDefinitions();
	public:
		GAME_IMPORT ttl::string_base<char> const presetEncodedString();
		GAME_IMPORT MED::CMaterialTemplate& operator=(MED::CMaterialTemplate const&);
		GAME_IMPORT void getMaterialParameters(ttl::list<MED::CMaterialTemplate::Parameter, ttl::allocator>&);
		GAME_IMPORT static std::initializer_list<ttl::string_base<char>>& fixedMaterialParametersCategories();
		GAME_IMPORT void clear();
#pragma endregion
	};

	struct TextList {
#pragma region GENERATED by ExportClassToCPPH.py
	public:
		GAME_IMPORT bool contains(ttl::string_base<char> const&) const;
		GAME_IMPORT TextList(std::initializer_list<ttl::string_base<char>>);
		GAME_IMPORT TextList(MED::TextList&&);
		GAME_IMPORT MED::TextList& operator=(MED::TextList&&);
		GAME_IMPORT TextList(MED::TextList const&);
		GAME_IMPORT bool starts(ttl::string_base<char> const&) const;
		GAME_IMPORT MED::TextList& operator=(MED::TextList const&);
		GAME_IMPORT bool match(ttl::string_base<char> const&) const;
#pragma endregion
	};

#pragma region GENERATED by ExportClassToCPPH.py
public:
	GAME_IMPORT MED::HeadType StringToHeadType(ttl::string_base<char> const&);
	GAME_IMPORT MED::SkeletonType StringToSkeletonType(ttl::string_base<char> const&);
	GAME_IMPORT ttl::string_const<char> editorSceneEnvprobeFilename(cbs::CComponent const&);
	GAME_IMPORT MED::EPropertyConfig operator|(MED::EPropertyConfig, MED::EPropertyConfig);
	GAME_IMPORT ttl::string_const<char> SkeletonTypeToString(MED::SkeletonType);
	GAME_IMPORT MED::SEditorSceneSetupData const* editorSceneSetupDataByPrefabName(ttl::string_const<char>);
	GAME_IMPORT ttl::string_base<char> join_strings(ttl::vector<ttl::string_base<char>, ttl::vector_allocators::heap_allocator<ttl::string_base<char>>, 1> const&, ttl::string_base<char> const&);
	GAME_IMPORT ttl::string_base<char> trimText(ttl::string_base<char> const&, char const*);
	GAME_IMPORT MED::EPropertyConfig operator&(MED::EPropertyConfig, MED::EPropertyConfig);
	GAME_IMPORT uint32_t splitIndexedString(ttl::string_base<char> const&, ttl::string_base<char>&, char const*);
	GAME_IMPORT bool operator==(MED::EnumItemType const&, MED::EnumItemType const&);
	GAME_IMPORT ttl::string_base<char> LodVisibilityPresetString(MED::LodVisibilityPreset);
	GAME_IMPORT MED::SEditorSceneSetupData const& editorSceneSetupData(MED::EditorSceneSetup);
	GAME_IMPORT ttl::string_base<char> join_strings(std::initializer_list<ttl::string_base<char>> const&, ttl::string_base<char> const&);
	GAME_IMPORT MED::ModelUsage ModelUsageFromFileName(ttl::string_const<char>);
	GAME_IMPORT bool operator!=(MED::EnumItemType const&, MED::EnumItemType const&);
	GAME_IMPORT bool operator!=(MED::EnumGroupType const&, MED::EnumGroupType const&);
	GAME_IMPORT ttl::string_const<char> StringFromModelUsage(MED::ModelUsage);
	GAME_IMPORT bool isRunningInEditor();
	GAME_IMPORT MED::TextList const& DefaultPlayersNames();
	GAME_IMPORT ttl::string_base<char> HeadTypeToString(MED::HeadType);
	GAME_IMPORT ttl::string_base<char> ModelSlotPresetTypeString(MED::ModelSlotPresetType);
	GAME_IMPORT MED::ModelUsage ModelUsageFromString(ttl::string_const<char>);
	GAME_IMPORT bool operator==(MED::EnumGroupType const&, MED::EnumGroupType const&);
	GAME_IMPORT MED::SkeletonType DetectSkeletonTypeFromName(ttl::string_base<char> const&);
	GAME_IMPORT ttl::string_base<char> join_strings(ttl::set<ttl::string_base<char>, ttl::less<ttl::string_base<char>>, ttl::allocator> const&, ttl::string_base<char> const&);
	GAME_IMPORT ttl::string_base<char> uniqueIndexedString(ttl::string_base<char> const&, char, std::function<bool ( ttl::string_base<char> const& )>);
	GAME_IMPORT ttl::string_base<char> normalizeToAscii(ttl::string_base<char> const&, char, ttl::string_base<char> const&);
	GAME_IMPORT bool disableRunningInEditor();
	GAME_IMPORT bool isRunningInGame();
	GAME_IMPORT void restoreRunningInEditor(bool);
#pragma endregion
};