#pragma once
#include <EGSDK\Imports.h>

class CRTTI;
class CRTTIField;

class rtti {
public:
	class IRttiFactory;
	class Type {
#pragma region GENERATED by ExportClassToCPPH.py
	public:
		GAME_IMPORT Type(char const*, rtti::IRttiFactory const&);
		GAME_IMPORT char const* GetClassNameA() const;
		GAME_IMPORT Type(char const*, rtti::IRttiFactory const&, char const*, int);
		GAME_IMPORT void AddField(CRTTIField*);
		GAME_IMPORT CRTTI const* GetNativeClass() const;
#pragma endregion
	};

#pragma region GENERATED by ExportClassToCPPH.py
public:
	GAME_IMPORT bool operator==(rtti::Type const&, CRTTI const*);
	GAME_IMPORT bool operator!=(rtti::Type const&, CRTTI const*);
	GAME_IMPORT bool operator==(CRTTI const*, rtti::Type const&);
	GAME_IMPORT bool operator!=(CRTTI const*, rtti::Type const&);
#pragma endregion
};