#pragma once
#include <EGSDK\Imports.h>
#include <EGSDK\Engine\ttl\string_base.h>
#include <EGSDK\Engine\ITextSerializer.h>
#include <EGSDK\Engine\ITextDeserializer.h>

class Uid {
#pragma region GENERATED by ExportClassToCPPH.py
	public:
		GAME_IMPORT static Uid const INVALID;

		GAME_IMPORT Uid(ttl::string_base<char> const&);
		GAME_IMPORT ttl::string_base<char> ToString() const;
		GAME_IMPORT bool operator!() const;
		GAME_IMPORT bool operator>(Uid const&) const;
		GAME_IMPORT Uid();
		GAME_IMPORT bool Write(ITextSerializer&, char const*) const;
		GAME_IMPORT bool operator<=(Uid const&) const;
		GAME_IMPORT Uid& operator=(Uid const&);
		GAME_IMPORT bool IsValid() const;
		GAME_IMPORT bool operator!=(Uid const&) const;
		GAME_IMPORT Uid(int64_t);
		GAME_IMPORT bool operator>=(Uid const&) const;
		GAME_IMPORT void FromString(ttl::string_base<char> const&);
		GAME_IMPORT bool Read(ITextDeserializer&, char const*);
		GAME_IMPORT void Generate();
#pragma endregion
};