#pragma once

namespace Anim {
    class IPoseElement;
}

namespace Audio {
    struct SAudioEventExtraData;
    struct SAudioEventExtraDataID;
}

namespace COFlags {
    enum TYPE;
}

namespace EBones {
    enum TYPE;
}

namespace EObjectToSimpleObjectsQueryResult {
    enum TYPE;
}

namespace LodDissolves {
    union SState;
}

namespace cbs {
    class CEntity;
    class CPointer;
}

struct AnimEventInfo;
class CHierarchyElement;
class CModelObject;
class CRTTI;
class IAnimBind;
class ICoSkeleton;
class IGSObject;
class IMpc;
class ISGChunk;
struct SCollision;
struct SMeshVisibilityParams;
struct SSurfParams;
struct TAnimId;
class aabb;
class extents;
struct uint4;

class __declspec(dllimport) IModelObject {
public:
    __cdecl IModelObject(void);
    __cdecl IModelObject(class IModelObject const&);
    virtual ~IModelObject(void);
    void AdjustExtentsToAllElements(bool, bool);
    virtual void AllowSkinsToModifyElementFlags(int, bool);
    class Anim::IPoseElement* AnimGetMeshPoseElement(void);
    class Anim::IPoseElement const* AnimGetMeshPoseElement(void) const;
    class Anim::IPoseElement* AnimGetModelObjectMorphPoseElement(void);
    class Anim::IPoseElement const* AnimGetModelObjectMorphPoseElement(void) const;
    class Anim::IPoseElement* AnimGetModelObjectPoseElement(void);
    class Anim::IPoseElement const* AnimGetModelObjectPoseElement(void) const;
    bool AnimReInit(class ttl::string_base<char> const&);
    virtual bool AreSkinsAllowedToModifyElementFlags(int) const;
    virtual unsigned int AttachAudioEvent(int, class ttl::string_base<char> const&, struct Audio::SAudioEventExtraData const*, class vec3 const&);
    virtual void AttachChildToMeshElement(class IControlObject*, int, bool);
    virtual enum EObjectToSimpleObjectsQueryResult::TYPE CanGoToSimpleObjectsEditor(void) const;
    virtual bool CharacterPresetExists(class ttl::string_base<char> const&) const;
    static void CollectMeshSkins(class ttl::string_base<char> const&, bool, class ttl::vector<class ttl::string_base<char>, class ttl::vector_allocators::heap_allocator<class ttl::string_base<char>>, 1>&);
    void CollectUsedTextures(class ttl::vector<class ttl::string_base<char>, class ttl::vector_allocators::heap_allocator<class ttl::string_base<char>>, 1>&);
    void CopyElementsPosition(class IModelObject*);
    virtual void DebugRenderElementBoxes(void);
    void DissolveObject(bool);
    virtual void DissolveObjectProgress(float, bool);
    void DumpAnims(void);
    virtual void ElementSetWorldMatrixFromQuatPos(int, class vec3 const&, float, class vec3 const&);
    virtual bool EnableCollisionsElement(int, bool);
    bool EnableElementPhysics(int, bool, bool);
    virtual bool EnableElementTraceColl(int, bool);
    void EnableHierarchySerialization(bool);
    virtual void EnableMotionBlur(bool);
    virtual void EnableRendering(bool);
    void EnableRenderingRayTracing(bool);
    void EnableRenderingScene(bool);
    void EnableRenderingShadows(bool);
    void EnableUpdateExtents(bool);
    virtual void ExecuteAnimActions(int, int, struct TAnimId, void const*, unsigned int);
    virtual void ForceUpdateAnimations(void);
    virtual void FromUpForwardPosElementLocal(int, class vec3 const&, class vec3 const&, class vec3 const&);
    virtual void FromUpForwardPosElementWorld(int, class vec3 const&, class vec3 const&, class vec3 const&);
    virtual void GatherMeshAndSkinName(class ttl::string_base<char>&, class ttl::string_base<char>&) const;
    class aabb const& GetAABBExtents(void) const;
    virtual class IAnimBind* GetAnimBind(void);
    virtual class IAnimBind const* GetAnimBind(void) const;
    virtual float GetAnimCurrentTime(struct TAnimId);
    virtual float GetAnimLength(class ttl::string_base<char> const&) const;
    virtual float GetAnimLength(struct TAnimId) const;
    virtual float GetAnimTimeDelta(void) const;
    virtual class ttl::string_base<char> GetAnimationFile(class ttl::string_base<char> const&) const;
    virtual struct TAnimId GetAnimationId(class ttl::string_const<char>, bool) const;
    void GetAnimationNames(class ttl::map<class ttl::string_base<char>, struct TAnimId, struct ttl::less<class ttl::string_base<char>>, class ttl::allocator>&);
    virtual class vec3 GetBoneDirVector(enum EBones::TYPE) const;
    virtual enum EBones::TYPE GetBoneIDFromMeshElem(int) const;
    virtual class vec3 GetBoneJointPos(enum EBones::TYPE) const;
    virtual class vec3 GetBonePerpVector(enum EBones::TYPE) const;
    virtual class ttl::string_base<char> GetCharacterName(unsigned int) const;
    virtual void GetCharacterNames(class ttl::string_base<char>&, class ttl::string_base<char>&);
    virtual int GetChildrenElementsNumber(int) const;
    int GetCurrentLOD(void) const;
    union LodDissolves::SState GetCurrentLodState(void) const;
    static enum COFlags::TYPE GetDefaultCOFlags(void);
    virtual int GetElementChild(int) const;
    virtual class extents GetElementExtentsInWorld(int) const;
    virtual class extents GetElementExtentsLocal(int) const;
    virtual unsigned int GetElementFlags(int) const;
    virtual int GetElementID(unsigned int) const;
    virtual int GetElementID(char const*) const;
    virtual int GetElementIDByLowercaseName(char const*) const;
    virtual int GetElementIndex(char const*) const;
    virtual void GetElementInvWorldMatrix(int, class mtx34&) const;
    virtual void GetElementLocalMatrices(int const*, unsigned int, class mtx34*);
    virtual class mtx34 const& GetElementLocalMatrix(int) const;
    virtual class vec3 GetElementLocalPos(int) const;
    virtual class ttl::string_base<char> GetElementName(int) const;
    virtual char const* GetElementNameCStr(int) const;
    virtual int GetElementNext(int) const;
    virtual int GetElementParent(int) const;
    virtual class extents GetElementReferenceExtents(int) const;
    virtual class mtx34 const& GetElementWorldMatrix(int) const;
    virtual class mtx34 GetElementWorldMtx(int) const;
    virtual class vec3 GetElementWorldPos(int) const;
    virtual int GetElementsNumber(void) const;
    char GetForcedAnimLod(void) const;
    virtual class CHierarchyElement* GetHElement(int) const;
    virtual float GetLastAnimApplyTime(void) const;
    virtual float GetLastAnimUpdateTime(void) const;
    float GetLodDissolveStep(void) const;
    virtual class vec4 const& GetMeshAttribute(unsigned int) const;
    virtual class mtx34 const& GetMeshAttributeMtx(unsigned int) const;
    virtual unsigned int GetMeshAttributesCount(void) const;
    virtual struct uint4 const& GetMeshColor(void) const;
    virtual class vec4 const& GetMeshColor(unsigned int) const;
    virtual bool GetMeshDataForSimpleObjectsEditor(class ttl::string_base<char>*, class ttl::string_base<char>*, __int64*, __int64*, int*);
    virtual int GetMeshElemFromBoneID(enum EBones::TYPE) const;
    void GetMeshElementsMatrices(class ttl::vector<class mtx34, class ttl::vector_allocators::heap_allocator<class mtx34>, 0>&) const;
    unsigned int GetMeshElementsMatricesCount(void) const;
    int GetMeshElementsState(class ttl::vector<unsigned char, class ttl::vector_allocators::heap_allocator<unsigned char>, 8>&, class ttl::vector<int, class ttl::vector_allocators::heap_allocator<int>, 2> const&) const;
    int GetMeshElementsStateSize(class ttl::vector<int, class ttl::vector_allocators::heap_allocator<int>, 2> const&) const;
    float GetMeshLodDistance(int) const;
    virtual class ttl::string_const<char> GetMeshName(void) const;
    struct SMeshVisibilityParams const* GetMeshVisibilityParams(void) const;
    float GetMeshVisibilityRange(void);
    static class IModelObject* GetModelObject(class IGSObject*);
    static class IModelObject* GetModelObject(class cbs::CEntity const*);
    static class IModelObject const* GetModelObject(class IGSObject const*);
    static class CRTTI const* GetNativeClass(void);
    unsigned int GetNumCollisionHullFaces(void) const;
    unsigned int GetNumCollisionHullPrimitives(void) const;
    unsigned int GetNumCollisionHullVertices(void) const;
    unsigned int GetNumSurfaceParams(void) const;
    unsigned int GetNumTraceHullFaces(void) const;
    unsigned int GetNumTraceHullPrimitives(void) const;
    unsigned int GetNumTraceHullVertices(void) const;
    virtual class cbs::CPointer<class ICoSkeleton> GetSkeleton(void) const;
    class ttl::string_const<char> GetSkin(void) const;
    virtual unsigned int GetSkinCount(void) const;
    virtual __int64 GetSkinMustHaveTags(void) const;
    virtual __int64 GetSkinMustNotHaveTags(void) const;
    virtual class ttl::string_const<char> GetSkinName(void) const;
    virtual void GetSkinName(unsigned int, class ttl::string_base<char>&) const;
    virtual int GetSkinSeed(void) const;
    static __int64 GetSkinTagsFromStr(char const*);
    struct SSurfParams* GetSurfaceParams(void) const;
    int GetTraceCollType(void) const;
    bool GetValidSkinsEditor(class ttl::vector<class ttl::string_base<char>, class ttl::vector_allocators::heap_allocator<class ttl::string_base<char>>, 1>&, class ttl::vector<class ttl::string_base<char>, class ttl::vector_allocators::heap_allocator<class ttl::string_base<char>>, 1>&) const;
    virtual float GetWaterCurrentSpeed(void);
    virtual class mtx34 const& GetWorldXform(void) const;
    virtual bool HideElement(int);
    virtual void HideElementsByMask(bool, class ttl::string_base<char> const&);
    virtual bool InitAnimSeqFile(class ttl::string_base<char> const&);
    virtual bool IsBiped(void) const;
    bool IsDefaultMeshLoaded(void);
    virtual bool IsElementABone(int);
    virtual bool IsElementCollsionsEnabled(int);
    virtual bool IsElementHidden(int) const;
    bool IsElementIDValid(int) const;
    bool IsElementPhysicsEnabled(int);
    virtual bool IsElementTraceCollEnabled(int);
    bool IsObjectDissolved(void) const;
    virtual bool IsRenderable(void) const;
    void LoadMesh(bool);
    void LoadMeshElements(class ISGChunk*);
    int MT_GetCount(void);
    char const* MT_GetName(unsigned int);
    float MT_WeightGet(unsigned int);
    static bool MeshAndSkinExists(class ttl::string_base<char> const&, class ttl::string_base<char> const&);
    static bool MeshExist(class ttl::string_base<char> const&);
    void MeshUseDefaultVisibilityParameters(void);
    void MoveElementBoxSide(int, int, float);
    void MoveElementBoxSides(int, class vec3 const&, class vec3 const&);
    void MoveElementBoxSides(int, float, float, float, float, float, float);
    virtual void OnAnimBindDestroyed(void);
    virtual void OnAnimEvent(struct AnimEventInfo const&);
    virtual void OnMpcCreated(class IMpc*);
    virtual unsigned int PlayAudioEvent(class ttl::string_base<char> const&, struct Audio::SAudioEventExtraData const*, class vec3 const&, class vec3 const&);
    virtual unsigned int PlayAudioEvent(unsigned int, struct Audio::SAudioEventExtraDataID const*, class vec3 const&, class vec3 const&);
    virtual class vec3 PointLocalToWorld(int, class vec3 const&);
    virtual class vec3 PointWorldToLocal(int, class vec3 const&);
    bool RaytestMe(class vec3 const&, class vec3&, unsigned short, bool, unsigned short);
    bool RaytraceMe(struct SCollision*, class vec3 const&, class vec3&, unsigned short, bool, unsigned short);
    bool ReplaceMaterial(class ttl::string_base<char> const&, class ttl::string_base<char> const&);
    void ResetBoneAndDescendantsToReferenceFrame(int);
    void ResetBonesExtentsToReferenceFrame(void);
    void ResetBonesToReferenceFrame(bool);
    void ResetElementsDescendantsToReferenceFrame(int);
    virtual void RestoreAnimationUpdateAbility(bool const&, class ttl::vector<bool, class ttl::vector_allocators::heap_allocator<bool>, 8> const&);
    virtual void RotateElement(int, class vec3 const&, float);
    void SaveMeshElements(class ISGChunk*);
    virtual void SetAudioEventSwitch(unsigned int, class ttl::string_base<char> const&, class ttl::string_base<char> const&);
    void SetBestGeomLods(void);
    virtual void SetBoneOrientation(unsigned char, class vec3 const&, class vec3 const&);
    virtual void SetCharacterNames(class ttl::string_base<char> const&, class ttl::string_base<char> const&);
    void SetDontApplyAnim(bool);
    virtual void SetElementExtentsLocal(class extents const&, int);
    virtual void SetElementLocalMatrices(int const*, unsigned int, class mtx34 const*);
    virtual void SetElementLocalMatrix(int, class mtx34 const&);
    virtual void SetElementLocalMatrixNoPropagate(int, class mtx34 const&);
    virtual void SetElementLocalPos(int, class vec3 const&);
    virtual void SetElementWorldMatrix(int, class mtx34 const&);
    virtual void SetElementWorldMatrixNoPropagate(int, class mtx34 const&);
    virtual void SetElementWorldPos(int, class vec3 const&);
    virtual void SetEngineObject(class CGSObject*);
    void SetExtentsLocal(class extents const&);
    void SetForcedAnimLod(char);
    virtual void SetInitializeMesh(bool);
    void SetLodDissolveStep(float);
    void SetLodStateForSpawnedObjects(union LodDissolves::SState);
    virtual void SetMeshAttribute(unsigned int, class vec4 const&);
    virtual void SetMeshAttributeMtx(unsigned int, class mtx34 const&);
    virtual void SetMeshColor(struct uint4 const&);
    virtual void SetMeshColor(unsigned int, class vec4 const&);
    void SetMeshCullSizeEnable(bool);
    bool SetMeshElementsMatrices(class ttl::vector<class mtx34, class ttl::vector_allocators::heap_allocator<class mtx34>, 0> const&);
    int SetMeshElementsState(class ttl::vector<unsigned char, class ttl::vector_allocators::heap_allocator<unsigned char>, 8> const&, class ttl::vector<int, class ttl::vector_allocators::heap_allocator<int>, 2> const&, bool, bool);
    void SetMeshLodDistance(int, float);
    virtual void SetMeshName(class ttl::string_const<char>);
    void SetMeshVisibilityRange(float);
    virtual void SetPivotPointFromElement(int);
    bool SetSkin(void);
    virtual void SetSkinMustHaveTags(__int64);
    virtual void SetSkinMustNotHaveTags(__int64);
    virtual void SetSkinName(class ttl::string_const<char>);
    bool SetSkinNoCharacterPreset(void);
    virtual void SetSkinSeed(int);
    void SetTraceCollType(int);
    virtual void SetupMeshPartClothSet(bool, bool, class ttl::vector<class ttl::string_base<char>, class ttl::vector_allocators::heap_allocator<class ttl::string_base<char>>, 1>*);
    bool ShouldApplyAnim(void) const;
    void ShowCollisionHull(bool);
    void ShowElementBox(class ttl::string_base<char> const&);
    void ShowElementBoxes(bool);
    void ShowElementBoxesFrom(class ttl::string_base<char> const&);
    void ShowElementBoxesFromTo(class ttl::string_base<char> const&, class ttl::string_base<char> const&);
    void ShowElementBoxesTo(class ttl::string_base<char> const&);
    void ShowExtents(bool);
    bool SkinExists(class ttl::string_base<char> const&);
    virtual void StopAnimActions(int, struct TAnimId, void const*, float);
    class CModelObject* ToCModelObject(void);
    class CModelObject const* ToCModelObject(void) const;
    virtual bool UnhideElement(int);
    virtual void UnlockAnimationUpdateAbility(bool&, class ttl::vector<bool, class ttl::vector_allocators::heap_allocator<bool>, 8>&);
    virtual class vec3 VectorLocalToWorld(int, class vec3 const&) const;
    virtual class vec3 VectorWorldToLocal(int, class vec3 const&);
};
