#pragma once
#include <EGSDK\Imports.h>

namespace Net::Repl {
	class CRttiInfo {
#pragma region GENERATED by ExportClassToCPPH.py
	public:
		VIRTUAL_CALL(0, uint64_t*, sub_C5A6F0, (char a1), a1);
#pragma endregion
	};
}